### ISSUE TITLE
How do I get the value from a Toast message using Selenium::Remote::Driver?

### ISSUE THREAD

**Issue by moezhirani** [gempesaw/Selenium-Remote-Driver#108]
On a certain action , a toast message pops up on the website that stays there for as much as 5 seconds. I need to get some information from this toast as it determines the next steps for my test.

Please help, Thanks, Regards,
Moez Hirani.

**Comment by Rashmi-Nuviso** [comment]
hi Moez ,

can you please help me to solve this issue .

am trying  to get the toast message for validation .

But am unclear about the steps .I have an use-case  where invalid username and password should throw an error "Bad credentials". this error message is coming from the server and captured as toast message for the UI to display it to the user .

**Comment by moezhirani** [comment]
Hi Rashmi,

I basically used a locator like - *//*[@id="toast-container"]/div/div* - to
identify the toast message. a '*find*' for that locator followed by '
*get_text*' worked fine for me. You may need to look through the code to
find out a good locator for your toastr object.

Finding the element was sometimes challenging (the toastr in my case showed
up after clicking a 'submit' button) , but I added a wait that lets jquery
to finish before looking for the element. For me, clicking the 'submit' was
causing some background processing to occur.

If you need a wait, then *wait_for_jquery *can be a helper function in your
framework that basically works by polling for the value of
$driver->execute_script('jQuery.active')' . As soon as this value is 0 , it
means the jquery has finished processing and you can continue with the test.

**Comment by Rashmi-Nuviso** [comment]
Thanks a lot Moez and gempesaw ,

your comments helped me to locate the toast-element.
for those who need help on this am pasting the python  snippet here .

 getErrorMsg = WebDriverWait(self.driver, 30).until(EC.presence_of_element_located(
                (By.XPATH, './/*[@id="toast-container"]/div/div[1][@class="toast-message"]')))
        logging.info(getErrorMsg.text)

hope it helps .!!!

Cheers !!
Rashmi BS.

**Comment by JeheenC** [comment]
Hey Guys!

I am facing similar situation, the web page that i am trying to automate using selenium IDE.So as i am trying to use the page to submit a request and when it's done submitting it throws a toast message for quick 4-5 secs at most. I have tried to to capture it using 
command = 'waitForElementPresent' 
target = 'css=span.md-toast-text.ng-binding'
then i used 
command = storedtext 
target = 'css=span.md-toast-text.ng-binding'
value = 'confirmation_ID'

Then i tried using the above info in the search box but that does not do it for me. And all the things you guys have mentioned isn't making any sense to me as i am not a developer/programmer as my background is in QA and this is something very new to me actually my second day messing with selenium ide. So can you guys break this down to me in simplest way as to how i can go about capturing the toast and use it to search for my request.. 

Any help what so ever in a promptly manner will be greatly appreciative.

Thanks in advance.

Jeheen

**Comment by moezhirani** [comment]
Hi Jeheen,

Could you please paste in the code that you are using ?

Moez.

**Comment by JeheenC** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://crm-qa.aiminspect.com/#/login" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/#/login</td>
	<td></td>
</tr>
<tr>
	<td>verifyTitle</td>
	<td>AiM CRM</td>
	<td></td>
</tr>
<tr>
	<td>verifyElementPresent</td>
	<td>id=username</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=username</td>
	<td>sample@aiminspections.com</td>
</tr>
<tr>
	<td>verifyElementPresent</td>
	<td>id=password</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=password</td>
	<td>testing</td>
</tr>
<tr>
	<td>verifyText</td>
	<td>//button[@type='submit']</td>
	<td>Log In</td>
</tr>
<tr>
	<td>click</td>
	<td>//button[@type='submit']</td>
	<td></td>
</tr>
<tr>
	<td>verifyTitle</td>
	<td>AiM CRM</td>
	<td></td>
</tr>
<tr>
	<td>verifyElementPresent</td>
	<td>link=New Request</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>link=New Request</td>
	<td></td>
</tr>
<tr>
	<td>waitForText</td>
	<td>css=span</td>
	<td>Inspection Request</td>
</tr>
<tr>
	<td>click</td>
	<td>id=customer-name</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=select_option_161</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=request-type</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=request-type</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=#select_option_165 &gt; div.md-text.ng-binding</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_7</td>
	<td>James Honda</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_8</td>
	<td>12345</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_9</td>
	<td>SL12345</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_10</td>
	<td>Mount rd and 13 mile</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_12</td>
	<td>Detroit</td>
</tr>
<tr>
	<td>click</td>
	<td>css=#select_value_label_2 &gt; span.md-select-icon</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=#select_option_68 &gt; div.md-text.ng-binding</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_15</td>
	<td>48212</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_26</td>
	<td>1</td>
</tr>
<tr>
	<td>click</td>
	<td>css=div.md-off</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_36</td>
	<td>2014</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_37</td>
	<td>Honda</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_38</td>
	<td>civic</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_39</td>
	<td>se</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_40</td>
	<td>5XDEG55679FSFSDF</td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_41</td>
	<td>SL1234</td>
</tr>
<tr>
	<td>click</td>
	<td>css=div.crm-color-dropdown-color.crm-color-dropdown-no-selected-color</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>xpath=(//button[@type='button'])[5]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>name=request.preferredDays[]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>document.inspectionForm.elements['request.preferredDays[]'][2]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>document.inspectionForm.elements['request.preferredDays[]'][4]</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>css=md-checkbox[name=&quot;sameAsDealerLocation&quot;] &gt; div.md-container.md-ink-ripple</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=input_35</td>
	<td>JEHEEN TEST</td>
</tr>
<tr>
	<td>click</td>
	<td>id=submit</td>
	<td></td>
</tr>

(after the submit is when the toast gets displayed.)

<tr>
	<td>waitForElementPresent</td>
	<td>css=span.md-toast-text.ng-binding</td>
	<td>confirmation_ID</td>
</tr>
<tr>
	<td>storeEval</td>
	<td>storeVars['span.md-toast-text.ng-binding']</td>
	<td>confirmation_ID</td>
</tr>
<tr>
	<td>click</td>
	<td>id=basic-search-input</td>
	<td>storeVars</td>
</tr>
<tr>
	<td>click</td>
	<td>id=submit</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//button[@type='button']</td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>

**Comment by Rashmi-Nuviso** [comment]
Hi Jeheen ,

you can try to locate the parent element first in the dom tree

as I have mentioned in my code [the one which is highlighted in bold] .



getErrorMsg = WebDriverWait(self.driver, 30).until(EC.presence_of_element_located(
(By.XPATH, **'.//*[@id="toast-container"]/div/div[1][@class="toast-message"]**')))
logging.info(getErrorMsg.text)


You need to capture this in real-time . 

suppose for example 
on click of an cart icon some item will be added to cart the message  which shows up  after clicking the cart icon in toast you need to click on that message and inspect  it using the firebug tool .

Since that the element where the message will be available will appear only for a few secs obviously you need to add the wait

**Comment by JeheenC** [comment]
Ok i will try to use the code you have provided. Thanks Rashmi !

**Comment by Rashmi-Nuviso** [comment]
Jaheen!!

 its just an example just follow the steps as i have  mentioned in the previous post .my code may not suit  your requirements .

**Comment by JeheenC** [comment]
Rashmi,

so i would use the code highlighted in bold as follows

Command = getEerrorMsg
Target = the code in bold

is this correct and add wait statements ...

**Comment by Rashmi-Nuviso** [comment]
getMsg = WebDriverWait(self.driver, 30).until(EC.presence_of_element_located(
(By.XPATH, 'paste your  toast Xpath here ]')))

print(getMsg.text)

hope this would help :)

**Comment by JeheenC** [comment]
thanks and sorry as i have very little exp with dealing coding and what not so therefore i apologize if i sound non techy person. 

But none the less thank you so much.

**Comment by abhishekkumar-tudip** [comment]
I am unable to get the xpath for the toaster message. Can anyone let me know how to get the xpath for the toaster message.

**Comment by harshwardhan27** [comment]
I am unable to get the xpath for the toaster message. Can anyone let me know how to get the xpath for the toaster message.

**Comment by harshwardhan27** [comment]
> I am unable to get the xpath for the toaster message. Can anyone let me know how to get the xpath for the toaster message.

Same problem with me as well.

**Comment by teodesian** [comment]
Getting xPaths for arbitrary elements on a web page is straightforward.
# Load your page up in firefox
# right-click on the relevant element, select the 'Inspect Element' option from the context menu summoned
# right click on the highlighted row in the inspector which should now have appeared below (or to the side) of your webpage
# choose the 'copy' option in the context menu, and then 'xpath' in the secondary menu.

This will copy the Xpath to your element into your paste buffer, and you can paste it to your heart's content.

The major complication here is that toast messages are an android specific abomination.  As such, you will have to use intrusive javascript techniques to grab it's selector, much as described in Gempesaw's earlier comment in this thread: https://github.com/teodesian/Selenium-Remote-Driver/issues/108#issuecomment-37682779

That said, it is generally in your best interest to stop using Xpath selectors.  They are easy to fool due to shadow DOM rendering differently on various browsers.  CSS selectors are much, much more reliable.  Given there are already competing versions of android, this may already be a problem in some cases.
