### ISSUE TITLE
set_window_size $height/$width cast problem

### ISSUE THREAD

**Issue by ricdainf** [gempesaw/Selenium-Remote-Driver#141]
Perl 5.18.2
Platform ubuntu 14.4
Using selenium 2.41 in standalone mode returned Exception : 
23:44:32.589 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Illegal (non-numeric) window width value passed: 1024
Build info: version: '2.41.0', revision: '3192d8a', time: '2014-03-27 17:17:32'
System info: host: 'darkstar', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-29-generic', java.version: '1.7.0_60'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.handler.SetWindowSize.setJsonParameters(SetWindowSize.java:41)

json created is : 
{"width":"1024","height":"1280"}
instead of : 
{"width":1024,"height":1280}

```
sub set_window_size {
    my ( $self, $height, $width, $window ) = @_;
    $window = ( defined $window ) ? $window : 'current';
    if ( not defined $height and not defined $width ) {
        croak "height & width of browser are required";
    }
####   PATCH  #####
    $height+=0;
    $width+=0;
####   PATCH  #####
    my $res = { 'command' => 'setWindowSize', 'window_handle' => $window };
    my $params = { 'height' => $height, 'width' => $width };
    my $ret = $self->_execute_command( $res, $params );
    if ( $ret =~ m/204/g ) {
        return 1;
    }
    else { return 0; }
}
```

Trying to pass casted values to subroutine have no result, suppose "my ( $self, $height, $width, $window ) = @_;" assignment resets the numeric data type to scalar raw

**Comment by gempesaw** [comment]
Thanks! Now on cpan as [v0.23](https://metacpan.org/release/GEMPESAW/Selenium-Remote-Driver-0.23)
