### ISSUE TITLE
method for get_implicit_wait_timeout

### ISSUE THREAD

**Issue by moezhirani** [gempesaw/Selenium-Remote-Driver#177]
While writing tests, often , we do not expect an element to be present.
Hence, we wrote a custom find_no_element subroutine that actually expects to not find an element.
In this case, you do not want to throw errors when elements are not found. Also you do not want to wait as much as you would when you do expect to find an element

Hence, I decided to use set_implicit_wait_timeout to define a lower timeout. However, once the test execution has exited this subroutine , the implicit_wait_timeout has to go back to the original value. In this case the get_implicit_wait_timeout might really help.

Example of how I am hoping to use the get_implicit_wait_timeout in our helper subroutine find_no_element:

    sub find_no_element {
        my ( $self, $locator, $options ) = @_;

        $options->{suppress_not_found_error} = 1;
   
        my $original_timeout = $self->get_implicit_wait_timeout;

        $self->set_implicit_wait_timeout(2000); # low timeout of 2 seconds

        my $elem = $self->_find_element( $locator, $options );

        $self->set_implicit_wait_timeout($original_timeout); # back to original timeout

        return ! $elem;
    }

**Comment by gempesaw** [comment]
We don't already have `get_implicit_wait_timeout`? Whoops.

err, wait, I don't see a documented endpoint for GETing the timeouts. That is, perhaps the webdriver server refuses to tell us?

https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/timeouts

It's entirely possible that the server does respond to the GET at `/timeouts`, but I haven't tried. Ah, and, thinking back to my current framework, what I've been doing is just setting the implicit wait timeout pretty frequently, perhaps each time before making a blocking request.

**Comment by peroumal1** [comment]
If you really want to store the timeout, you could subclass Selenium::Remote::Driver and add a timeout attribute. 
```perl
package SeleniumSubclass; 
use Moo; 
extends Selenium::Remote::Driver; 

has 'timeout' => ( 
     is => 'rw',
     trigger => sub { 
         my $self = shift; 
         $self->set_implicit_wait_timeout($_[0]); 
    }, 
); 

1; 
```

So this way, every time you modify the timeout, you will have the 'set_implicit_wait_timeout' method called on the driver. You can also easily have the value from the timeout before it gets modified, by doing : 

```perl
my $original_timeout = $self->timeout; 
$self->timeout($new_timeout); 
..
$self->timeout($original_timeout); 
```

Hope it helps !

**Comment by gempesaw** [comment]
thanks for the timeout idea. closing as there's no endpoint in the JSONWireProtocol to add :(

**Comment by moezhirani** [comment]
Thanks everyone for the responses !
