### ISSUE TITLE
body_text_unlike in T::S::R::D

### ISSUE THREAD

**Issue by glenwolf** [gempesaw/Selenium-Remote-Driver#180]
Calling any of the `body_text_` tests (i.e. body_text_like, body_text_contains, etc.) from Test::Selenium::Remote::Driver performs the test as expected, but does not print the provided error message. However, if a `body_text_` test fails, the output from the `Test` method is printed, implying that the `body_text_` method is failing to forward the provided error message to the `Test` method that it calls.

EDIT:
example test:
 `$twd->body_text_unlike( qr/not viewable/, "Page or item is viewable to you" );`

success yields `ok 1`
failure yields
```
not ok 1
#   Failed test at /Users/redshirt/some_test.t line 41.
#          got: "Beta\Topics\x{0a}\x{0a}\x{0a}\x{0a}"...
#       length: 10744
#     doesn't match '(?^:not viewable)'
```

**Comment by peroumal1** [comment]
Can you provide an example of a failing snippet of code please ?

**Comment by glenwolf** [comment]
Added to original error

**Comment by peroumal1** [comment]
See my comment :)

**Comment by peroumal1** [comment]
@gempesaw do you mind if I integrate the fix for this on the branch from #179 ?

**Comment by gempesaw** [comment]
I think you actually already fixed that in #179. The `my $desc` in the two branches of that `if` were changed to just `$desc`. Or maybe I'm thinking of the wrong if branch. Either way, sure!

**Comment by peroumal1** [comment]
Unlikely, what I fixed was for the `content_` functions, I guess the
problem is still there for the functions mentionned.
Le 23 janv. 2015 17:52, "Daniel Gempesaw" <notifications@github.com> a
écrit :

**Comment by glenwolf** [comment]
Man do I love responsive communities xD

You guys rock!

**Comment by gempesaw** [comment]
Hmm I've really got to figure out an automated way to update the windows mocks. Well, yeah, presuming all tests are passing this'll go out with 0.23, perhaps tonight or tomorrow. :D

**Comment by peroumal1** [comment]
Just thinking out loud, with a Browserstack or Saucelabs access, could we
possibly automate the generation of the mocks ?

On Fri, Jan 23, 2015 at 7:39 PM, Daniel Gempesaw <notifications@github.com>
wrote:

> Hmm I've really got to figure out an automated way to update the windows
> mocks. Well, yeah, presuming all tests are passing this'll go out with
> 0.23, perhaps tonight or tomorrow. :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gempesaw/Selenium-Remote-Driver/issues/180#issuecomment-71241824>
> .
>



-- 
Peroumalnaik Emmanuel

**Comment by glenwolf** [comment]
Hey, that's great to hear! :D

**Comment by gempesaw** [comment]
Thanks! Now on cpan as [v0.23](https://metacpan.org/release/GEMPESAW/Selenium-Remote-Driver-0.23)
