### ISSUE TITLE
alert_is_present?

### ISSUE THREAD

**Issue by hoodie63** [gempesaw/Selenium-Remote-Driver#185]
In the Java version there is a call alertIsPresent, so you can find out if there is an open alert before attempting to access it.

That doesn't seem to be implemented here. And if I call get_alert_text() when an alert isn't shown, the whole thing dies a horrible death.

Part of my test needs to be that an alert opened when it should.  It should fail the test if the alert isn't there, but it should crash everything.

Is there someway that I've missed to determine if an alert is open?

Nevermind - sorry.  I was looking in the wrong place.

**Comment by hoodie63** [comment]
OK, so I thought I found alert_is_present(), but it's in WWW::Selenium, not in the Driver.

Is there a way to use those commands? 

If not, are there plans to implement that call in Driver?

**Comment by gempesaw** [comment]
The JSONWireProtocol doesn't have a built-in predicate for alert presence. It seems like the recommended strategy is to try interacting with the alert and catch the exception. 

```perl
use Try::Tiny;
sub is_alert_present {
    my ($driver) = @_;

    try {
        $driver->get_alert_text;
        return 1;
    }
    catch {
        return 0;
    };
}
```

Or alternatively, try interacting with the page and catch the AlertIsPresent exception. (For whatever reason, there seems to be a 2 second timeout on getting alert text. It seems like it should be one of the custom timeout settings, but I couldn't find it.) The following method does the same thing but slightly faster:

```perl
use Try::Tiny;
sub faster_is_alert_present {
    my ($driver) = @_;

    try {
        $driver->get_title;
        return 0;
    }
    catch {
        return 1;
    };
}
```

This should work with your try/catch package/method of choice, including `eval/$@`. You may want to get more savvy and check against the thrown error that you're catching the exception you intended for.

We could put something like that in S:R:D.

(As far as I know, there's no way to access WWW::Selenium from a webdriver session. I've read about something called WebdriverBackedSelenium, which is ... some sort of bridge-adapter thingie between RC and webdriver, but I've never used it and I believe it was deprecated a few years ago....)

**Comment by hoodie63** [comment]
Thanks, that does work. I guess I'll add that to my wrappers.
