### ISSUE TITLE
Plugins/extensions for S::R::D

### ISSUE THREAD

**Issue by peroumal1** [gempesaw/Selenium-Remote-Driver#188]
I've been wondering, would it be a good idea to introduce the ability to use plugins or extensions with S::R::D ? 
We could have an alternate namespace (like SeleniumX::YourExtension) that would contain all the extensions.
It would allow us to do something that is quite hard to do for the moment being : separate specific behaviour requests (like not croaking on find_ functions) from the main code base. 
What do you say @gempesaw ?

**Comment by gempesaw** [comment]
Sure, I haven't done that before. Do we have to do anything in our code to allow/enable this, or is it just a convention thing that we'd stick to and advise users to follow? I think @jamadam mentioned this last year at some point as well along with autoloading all the plugins in a particular namespace. How would it work ?

**Comment by peroumal1** [comment]
To be honest, I haven't dug the idea much so I have no idea on how we would do that. 
Either in the case of plugins or extensions, we would have to follow at least a namespace convention (for instance the extensions to Moo are in the MooX:: namespace).
As for what we need to enable in our code, that's a good question ... I would say nothing so far, but I guess it would depend on what we need to achieve. 
We could try on some enhancement (which one ?) to implement this and assess then the difficulty.
