### ISSUE TITLE
How to use through proxy?

### ISSUE THREAD

**Issue by guyaparker** [gempesaw/Selenium-Remote-Driver#190]
I've been trying to connect through a proxy without success unless I create my own $ua. Has something changed or am I missing something?

I've exported http_proxy and https_proxy and then tried each of the following:

'proxy' => { 'proxyType' => 'system' },
'proxy' => { 'proxyType' => 'manual', 'httpProxy' => 'xx.xx.xx.xx:8080', 'sslProxy' => 'xx.xx.xx.xx:8080' },
'proxy' => { 'proxyType' => 'pac', 'proxyAutoconfigUrl' => 'http://xx.xx.xx.xx/proxy.pac' },

But the connection is never made.

If I create my own $ua and set it's env_proxy and use that then the connection does work:

my $ua = LWP::UserAgent->new;
$ua->env_proxy;
my $driver = new Selenium::Remote::Driver('remote_server_addr' => $host, 'port' => "80", 'ua' => $ua);

Is there some magic I'm missing where I don't need to create my own $ua?

Thanks!

**Comment by gempesaw** [comment]
The proxy you're putting on `$ua` would be used for the communication between the perl code and the web driver server - is that what you're trying to do? 

To use a proxy with Firefox, you need to create a custom Firefox profile. I could entertain the argument that we should do this for you, perhaps. 

If you ask for `browser_name = 'chrome'`, you should be able to use the proxy setting in our constructor as a browser level proxy.

http://blog.danielgempesaw.com/post/86683745978/playing-with-the-new-perl-bindings-for-the

**Comment by guyaparker** [comment]
The perl code is connecting to SauceLabs from behind a proxy, yes.
So is creating and using a $ua expected in that situation?
The proxy settings for Selenium::Remote::Driver are just for configuring the remote browser?

**Comment by gempesaw** [comment]
Ah, okay, yes, if you want the perl to use a proxy then your only recourse is to use your own `$ua`. The proxy settings, as you say, are for configuring the browser itself.

**Comment by guyaparker** [comment]
OK, thanks. Totally did not understand that!

**Comment by gempesaw** [comment]
:)
