### ISSUE TITLE
Is there a way to ignore zoom level setting in Selenium Webdriver using PERL?

### ISSUE THREAD

**Issue by SeanArkin** [gempesaw/Selenium-Remote-Driver#193]
Hello,

Im new here, not sure if Im writing in a proper page. I have a automated test scripts against a web app with lengthy menus so I need to decrease the level of IE zoom to see the lease menu. However when I run the script, error will occur that cause the script not to run. The error is 22:15:48.990 WARN - Exception: Unexpected error launching Internet Explorer. Bro
wser zoom level was set to 94%. It should be set to 100% (WARNING: The server di
d not provide any stacktrace information)
Appreciate your help friends

**Comment by gempesaw** [comment]
hi! from a quick [google](https://www.google.com/search?sourceid=chrome-psyapi2&ion=1&espv=2&es_th=1&ie=UTF-8&q=internetexplorerdriver%20zoom&oq=internetexplorerdriver%20zoom&aqs=chrome..69i57.5023j0j7) there seems to be an desired capability you can use: `ignoreZoomSetting`

you wanna try the following ?
```perl
# warning: untested code...
my $ie = Selenium::Remote::Driver->new_from_caps(
    desired_capabilities => {
        ignoreZoomSetting => JSON::true
        browserName => 'internet_explorer'
    }
);
```

**Comment by SeanArkin** [comment]
Hi gempesaw,

Thank you for your response. I tried both but has an error. I like the second suggestion since I really dont waht to make the zoom level less than 100%. 
Re mouse_move_to_location, the mouse pointer is not moving to the indicated element. BTW, I use the xpath of the element for $lease_menu_elem. Here is my samplet code.

eval{$driver->mouse_move_to_location(element => $xpath)}; 
if($@)
{
        $result = 'Fail';
}
else
{
	$result = 'Pass';
}

**Comment by gempesaw** [comment]
Ah, you need to pass the `element` argument an actual Selenium::Remote::WebElement, not an `$xpath` string. Like the example above, 

```perl
# untested...
my $xpath = '//html';
my $lease_menu_web_elem = $driver->find_element( $xpath );
$driver->mouse_move_to_location( element => $lease_menu_web_elem );
```

**Comment by SeanArkin** [comment]
Hi gempesaw,

It works. Thanks so much for your help
