### ISSUE TITLE
release a version of S:R:D in tandem with the next version of selenium-webdriver

### ISSUE THREAD

**Issue by gempesaw** [gempesaw/Selenium-Remote-Driver#201]
Heard briefly in the IRC channel that they're aiming to do another release soon (this week? next week?). Now that we're launching browsers, we need to follow up with a release shortly after theirs in order to keep our Firefox extension up to date, amongst other dependencies that we now have upon the official project. 

~~I think v0.26 will correspond to selenium-webdriver-2.46.0.~~
v0.26 is ready sooner than the next webdriver version; we'll use another release for 2.46.0.

**Comment by gempesaw** [comment]
http://selenium-release.storage.googleapis.com/index.html?path=2.46/

ok 2.46 is out

gotta copy the firefox-specific stuff out of the jar and into our project. bit of a pain, perhaps it should be automated...

**Comment by peroumal1** [comment]
I read the changelog ... are you talking about the Marionette stuff ?

**Comment by gempesaw** [comment]
oh, maybe ? I didn't even look at the changelog yet. It's entirely possible things have changed. 

The way I set up the Firefox auto-launching was that it installed the `webdriver.xpi` into a new Firefox profile. Apparently there isn't a standalone FirefoxDriver binary the way there is a Chromedriver for Chrome or ghostdriver for PhantomJS. But, I presume there'd be changes in `webdriver.xpi` across builds of Webdriver to handle newer versions of Firefox so that's why I'd want to update it. 

But yea you raise a good point, if the firefox extension `webdriver.xpi` hasn't changed then this is a no-op...

**Comment by gempesaw** [comment]
https://github.com/gempesaw/Selenium-Remote-Driver/commit/e251f6ddbb11cf7e1b88a6e9654b49a6474feb0c fixes this.
