### ISSUE TITLE
FireFox user_agent

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#202]
Does anyone know how to set a firefox user-agent in extra_capabilities when using firefox as the selenium browser? I'd like to use different firefox user-agents in my tests.

**Comment by gempesaw** [comment]
You have to pass a firefox profile during instantiation; firefox doesn't take settings during instantiation the way chromedriver does. You can use Selenium::Firefox::Profile to help you do this, if you'd like. I actually have to accomplish this exact task for work today, so if you give it a couple hours, I'll update with how I manage it.

**Comment by tranwave** [comment]
Excellent, I'll wait, thanks!

**Comment by gempesaw** [comment]
```perl
#! /usr/bin/perl

use strict;
use warnings;

use feature qw/say/;
use Selenium::Remote::Driver;
use Selenium::Firefox::Profile;

my $profile = Selenium::Firefox::Profile->new;
$profile->set_preference(
    'general.useragent.override' => 'our custom user agent!'
);

my $firefox = Selenium::Remote::Driver->new(
    firefox_profile => $profile
);

$firefox->get('http://whatsmyuseragent.com/');
say $firefox->find_element_by_class('info')->get_text;

say $Selenium::Firefox::Profile::VERSION;
say $Selenium::Remote::Driver::VERSION;
```

```
$ perl -w /tmp/perl.pl
our custom user agent!
0.25
0.25
```

The above works if you want to use Selenium::Remote::Driver. I'm working on a fix now for specifying a firefox profile with Selenium::Firefox, but as of v0.25, Selenium::Firefox just ignores the `firefox_profile` argument in its constructor.

**Comment by tranwave** [comment]
Can I continue to use other selenium variables in the hash say, 

my $firefox = Selenium::Remote::Driver->new(
    firefox_profile => $profile,
    'proxy' => { 'proxyType' => 'manual', 'httpProxy' => $this->{Proxy}.":".$this->{ProxyPort}},
);

and with a firefox profile do I still have to use 'browser_name' => 'firefox'?

**Comment by gempesaw** [comment]
You can use it with other attributes, but the particular one you named, proxies, need to be set up in the Firefox::Profile object. Last I checked, the remote driver server doesn't respect capability proxy settings for Firefox; the settings need to be manipulated in the profile. I also need to figure out the proxy thing so I will post that here too in a moment.

The default browser name is firefox, so that's why it works while being left out. If you were to change `browser_name` to something other than firefox, I'd expect that you'd run into issues.

**Comment by gempesaw** [comment]
https://github.com/gempesaw/Browsermob-Proxy/blob/f1f67ffd5ebf25906ac5ef3296be5ccabb480938/lib/Browsermob/Proxy.pm#L392

perhaps these are the additional preferences you need to set in your profile object before instantiating the driver:

```perl
        'network.proxy.type' => 1,
        'network.proxy.http' => $self->server_addr,
        'network.proxy.http_port' => $self->port,
        'network.proxy.ssl' => $self->server_addr,
        'network.proxy.ssl_port' => $self->port
```

untested, although I wrote it in the first place, so presumably a previous version of me verified that it worked...

**Comment by tranwave** [comment]
so I'm assuming my $proxy = new Browsermob::Proxy( 'server_addr' => '192.168.1.1', 'port'=>'9991' )
 instead of just my $proxy = Browsermob::Proxy->new;
?

**Comment by gempesaw** [comment]
yeah, that'd work.

For the args to Browsermob::Proxy, it uses `server_port` for the port of the running BMP server, and `port` for the port of the proxy that will be returned to you. So your example would've sent a POST to 192.168.1.1:8080/proxy/9991. 

I've made the assumption that you wanted to use a proxy to do something with the HTTP traffic from your browser. But, I made the same assumption and was wrong before in #190 , when they wanted to use a proxy for the $ua connection. See that ticket if that's what you're trying to do.

**Comment by tranwave** [comment]
I have a squid proxy server and I want to use that proxy for proxy browsing such as:

                $this->{Driver} = new Selenium::Remote::Driver(
                    'proxy' => { 'proxyType' => 'manual', 'httpProxy' => $this->{Proxy}.":".$this->{ProxyPort}},

so I don't see where to set the proxy address and port with your firefox profile using Browsermob. I'm not using a Browsermob server...

**Comment by gempesaw** [comment]
ah, sorry for confusing you. do you want your perl code to talk over the squid proxy? or, do you want the selenium browser to talk over the squid proxy ?

if you want your perl code to talk to webdriver across the squid proxy, you can either pass S:R:D your own `LWP::UserAgent` instance with the proxy settings set, as in the first post of #190 , or set the [appropriate environment variables (http_proxy, https_proxy, ssl_proxy)](https://github.com/gempesaw/Browsermob-Proxy/blob/f6cf119dad56cd8beeab26cd512fa378b7aaf55c/lib/Browsermob/Proxy.pm#L441) manually.

if you want the selenium browser's traffic to go across the squid proxy, you need to define the aforementioned properties in your firefox profile

```
        'network.proxy.type' => 1,
        'network.proxy.http' => $server_addr,
        'network.proxy.http_port' => $port,
        'network.proxy.ssl' => $server_addr,
        'network.proxy.ssl_port' => $port
```

with `$profile->set_preference`.

**Comment by tranwave** [comment]
Oh excellent! Yeah I just needed to how to set:
 'network.proxy.type' => 1,
        'network.proxy.http' => $server_addr,
        'network.proxy.http_port' => $port,
        'network.proxy.ssl' => $server_addr,
        'network.proxy.ssl_port' => $port

so set_preference is what I needed. Thanks so much, you were a huge help!

**Comment by gempesaw** [comment]
cheers :D
