### ISSUE TITLE
Unable to find element inside an iframe

### ISSUE THREAD

**Issue by SeanArkin** [gempesaw/Selenium-Remote-Driver#205]
Hello,

I am using PERL as my programming language. I need to click a certain icon but the location of the element to click is inside the iFrame. I tried to use switch_to_frame but I can't get the correct frame number that's why the script is failing. Below is the structure of the html

html
 head /head
 body
 iframe /iframe
 iframe /iframe
 iframe
   "The element is here"
/iframe
/body
/html

I removed the "<>"

**Comment by SeanArkin** [comment]
I think I got already.
$driver->switch_to_frame();
$driver->switch_to_frame(2);

**Comment by peroumal1** [comment]
Did you have a look at the [documentation](https://metacpan.org/pod/Selenium::Remote::Driver#switch_to_frame) ? 
If you want to switch to a iframe, you can use `find_element` in conjunction with `switch_to_frame`. 
Let's say your HTML looks like this : 
```html 
<html> 
<head> </head>
<body> 
<iframe id="id1"></iframe>
<iframe id="id2">YOUR ELEMENT</iframe> 
</body>
</html>
```
You could switch to the iframe with : 
```perl 
my $iframe = $driver->find_element("//iframe[\@id='id2']");
$driver->switch_to_frame($iframe);
```

I did not test the snippet I'm providing, but if there is still something wrong, feel free to tell :)

**Comment by gempesaw** [comment]
if you're still having issues, feel free to open another issue. thanks!
