### ISSUE TITLE
can't call method workbooks on unblessed reference

### ISSUE THREAD

**Issue by SeanArkin** [gempesaw/Selenium-Remote-Driver#206]
Hi,

I am getting this error can't call method workbooks on unblessed reference when writing to excel file. The weird thing is that if I run the script manually, no error is encountered. But when I run via third party system (Internal Tool to run automated script), the error occur.
Snippets
	sub init
	{
		my $directory = &getcwd;
		&edit_excel ( "$directory/$fname" );
	}
   
	sub edit_excel
	{
		$row3++;
		my ( $xl_report3 ) = @_;
		my ( $excel3, $workbook3, $sheet3 );
		
		$excel3 = CreateObject OLE 'Excel.Application';
		$excel3 -> {Visible} = 0;
     
		$workbook3 = $excel3    -> Workbooks  -> Open ( "$xl_report3" ) or &terminate ( "open $xl_report3" );      ""The error is in this line""

		$sheet3    = $workbook3 -> Worksheets -> {$testCaseID};
		$sheet3 -> Range ( 'L'.$row3 ) -> {Value} = $result;
		$excel3 -> {DisplayAlerts} = 0;
		$workbook3 -> Save;
		$workbook3 -> Close;
		$excel3    -> Quit;

**Comment by peroumal1** [comment]
Hello, 

Unfortunately we cannot help you with that, we provide support only for `Selenium::Remote::Driver`.

**Comment by SeanArkin** [comment]
Thanks poroumal1. Yeah you are correct this is not the right place for this though this is a part of my Selenium project
