### ISSUE TITLE
Wait Until Full Page Load to Find an Element?

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#207]
I noticed using Perl Selenium-Remote-Driver 0.17 and Selenium 2.39.0 server through proxies is a bit of a problem. I use 0.17 Perl API because I haven't been able to wrap/compile my perl applications with ActiveState PerlApp using 0.25. I have a squid proxy server running a couple proxies that is on the same network as the selenium server. When I use proxies the browser takes a long time before the page fully loads, even though mostly all the elements have been loaded. Is there a way to search and manipulate the xpath elements before the page fully loads? Maybe new version of both the API and Selenium server? If there's no way around this, does PhantomJS have the same issue?

**Comment by gempesaw** [comment]
>  I use 0.17 Perl API because I haven't been able to wrap/compile my perl applications with ActiveState PerlApp using 0.25

oh? what kind of errors are you getting ? I don't know anything about activestate or perlapp, so I'll probably be of little to no help, but I'm a bit curious.

> When I use proxies the browser takes a long time before the page fully loads, even though mostly all the elements have been loaded. Is there a way to search and manipulate the xpath elements before the page fully loads?

You can try the `page load` [timeout](https://metacpan.org/pod/Selenium::Remote::Driver#set_timeout) 

```perl
# for a slow loading page, will block for at most 12.345 seconds
$d->set_timeout( 'page load', 12345);
```

( You'll have to try/catch the exception if your page exceeds the timeout time, btw )... Alternatively, can your squid proxies set request_timeouts on their connections? I'm having somewhat of a similar issue with my proxy and Selenium's page load timeout isn't helpful, but setting a request timeout on the proxy itself is helpful.

> If there's no way around this, does PhantomJS have the same issue?

no idea! i don't use phantomjs much any more.

**Comment by tranwave** [comment]
Hmm how would the set_timeout with selenium enable me to still read the elements even though the page hasn't loaded yet. I could catch the exception and then search the element again but sometimes the page just spins and spins no matter what.

**Comment by gempesaw** [comment]
Oh, I didn't actually check whether `find_element` is willing to look for an element on a page that is still loading some resources. Did you try it - does `find_element` also block like `get` ?

```perl
$d->set_timeout( 'page load', 100);
eval { $d->get('slow-page.com') };
$d->find_element('*', 'css');
```

> There needs to be a stop page load function just like there is a refresh function,

There isn't a webdriver endpoint for stop, but you can just call javascript's `window.stop` after catching your exception.

```perl
$d->execute_script('window.stop()');
```

And, if neither of those work, look into Squid proxy's ability to set request timeouts. You should be able to set an upper bound cut off for a request and the page should just finish loading in the browser after the upper bound seconds at most, transparently to webdriver.

**Comment by tranwave** [comment]
Thank so much for that knowledge my friend. I'll try both methods. I don't see why window.stop() wouldn't work, actually sounds like exactly what I'd like to do.

**Comment by gempesaw** [comment]
if you run into issues, feel free to open a new issue. thanks!
