### ISSUE TITLE
Is it possible simple implement something like "failing test callback"?

### ISSUE THREAD

**Issue by tomas-zemres** [gempesaw/Selenium-Remote-Driver#209]
This request is related to this solved issue: https://github.com/gempesaw/Selenium-Remote-Driver/pull/203

Implemented "error_callback" works fine, but it is called only if "find_element_*" failed.

I need some callback that is executed if any test in "selenium-test-methods" ( *_ok *_like *_contains ....) failed,
so that my application may automatically take a screenshot on error or failing-test.

I have implemented this functionality using Test::WWW::Selenium and it's "error_callback", and I would like to migrate to module Test::Selenium::Remote::Driver).

Thank you.

**Comment by peroumal1** [comment]
What do you mean by "selenium-test-methods" ? Are you referring to [Test::Selenium::Remote::Driver](https://metacpan.org/pod/Test::Selenium::Remote::Driver) methods ? 

If this is the case, as Test::Selenium::Remote::Driver inherits from Selenium::Remote::Driver, what was implemented in #203 should be available for Test::Selenium::Remote::Driver.
This means that you can write : 
```perl 
my $driver = Test::Selenium::Remote::Driver->new(error_handler => sub { print 'foo' }); 
```
And then the error handler will be called should a `_ok` or `_like` test fails. 
If that is not the case, feel free to tell us so we can fix the implementation.

**Comment by gempesaw** [comment]
Do you have an example of the error_handler not working as you expect? It seems to be working fine with T:S:R:D for me in v0.26 for non-`find_element` type exceptions:

```perl
#! /usr/bin/perl

use strict;
use warnings;
use Test::Selenium::Remote::Driver 0.26;
use Test::More;

my $called = 0;

{
    my $d = Test::Selenium::Remote::Driver->new(
        error_handler => sub { $called++; }
    );
    # this throws since there's no alert present
    $d->dismiss_alert_ok;
    $d->quit;
}

is($called, 1,
   'error handler was invoked when dismiss alert threw an exception');

done_testing;
```

I noticed briefly during testing that when using the `Selenium::Chrome` module, the `chromedriver` binary doesn't actually throw exceptions the same way that the `selenium-server.jar` does, so we actually don't get an `die` at all in our perl code. Was that what you were doing ?

**Comment by tomas-zemres** [comment]
Yes, I refer to Test::Selenium::Remote::Driver methods.

for example 'body_text_contains', try following example:
```perl
use Test::Selenium::Remote::Driver;

use strict;
use warnings;
use Test::Selenium::Remote::Driver 0.26;
use Test::More;
use Carp;

# Test find_element_ok
{
    my $d = Test::Selenium::Remote::Driver->new(
        remote_server_addr  => $ENV{SELENIUM_HOST},
        port                => 4444,
        error_handler => sub {
            print STDERR "CALLBACK: find_element_ok failed\n\n";
        }
    );

    $d->get_ok('https://www.google.com');

    $d->find_element_ok('asdkjadsjklasd');
    $d->quit;
}

# Test body_text_contains
{
    my $d = Test::Selenium::Remote::Driver->new(
        remote_server_addr  => $ENV{SELENIUM_HOST},
        port                => 4444,
        error_handler => sub {
            print STDERR "CALLBACK: body_text_contains failed\n\n";
            croak $_[1];
        }
    );

    $d->get_ok('https://www.google.com');

    $d->body_text_contains('asdkjadsjklasd');
    $d->quit;
}

done_testing.
```

first callback is called, because it use "find_element", but second callback is not called even if body_text_contains failed.

**Comment by tomas-zemres** [comment]
Note that I say about failing tests that does not raise any exception.

**Comment by peroumal1** [comment]
You are totally right, there is an issue with that. 
When calling `body_text_contains`, what happens is : 
 * a call to `get_body`
 * a comparison with the string passed as a parameter to check if the text is present in the body 

As the call to `get_body` does not fail, the handler ends up never being called, since it was made to catch failing webdriver calls. 

I think there are other functions that are built the same way, maybe I can come up with a fix, but it looks non-trivial...

**Comment by peroumal1** [comment]
I have pushed a new branch, which should fix the behaviour for all the T::S::R::D functions. Can you try it and tell if this fixes your problem ?

**Comment by tomas-zemres** [comment]
I try it.

**Comment by tomas-zemres** [comment]
I'm using for example body_text_contains, and it now calls error_handler correctly (if test failed).

Thank you.
