### ISSUE TITLE
T::S::R::D doc outdated

### ISSUE THREAD

**Issue by faelin** [gempesaw/Selenium-Remote-Driver#211]
(note: I have the latest cpan version of T::S::R::D)

It seems that certain functions (specifically, clear_element_ok and click_element_ok) need their doc updated. The documentation claims that args are `$twd->click_element_ok($search_target [,$desc])`, but my code required `( $target, $locator, $desc )` to run.

**Comment by peroumal1** [comment]
Hello, 

I just tried the following snippet with S::R::D 0.26 

```perl 
#! /usr/bin/perl

use strict;
use warnings;
use Test::Selenium::Remote::Driver;
use Test::More;

my $t = Test::Selenium::Remote::Driver->new;
$t->get('https://en.wikipedia.org/wiki/Main_Page');
$t->click_element_ok("//*[text()='Arts']",'clicked ok');
$t->pause('2000');
done_testing;
```

... and it is working. 


We introduced locators as parameters for functions relying on `find_element` a while ago, so that users can specify a locator (xpath, css, id, class ...) when using those functions. 
Normally, the locator should default to xpath when not specified (as shown in my example), so the transition from the old parameter list to the new one (with locator) should be seamless. 

Can you give an example of what you had that is not working ? 

As for the documentation, of course it should be updated, thank you for the report :+1:

**Comment by faelin** [comment]
Ah, I think I know what I did wrong. I forgot that it defaults to path.
Setting the `default_finder` argument during $twd creation doesn’t seem to
change that behavior, though (it’s set to css now).

`my $twd = Test::Selenium::Remote::Driver->new( default_finder => 'css',
javascript => 1 );`
` $twd->click_element_ok("#preview_0 a.btn", 'css', "'Prieview comment'
button exists”);`

The above works, but not if you remove the ‘css’ argument from the click
command.



On Friday, June 5, 2015, peroumal1 <notifications@github.com> wrote:
> Hello,
>
> I just tried the following snippet with S::R::D 0.26
>
> #! /usr/bin/perl
>
> use strict;
> use warnings;
> use Test::Selenium::Remote::Driver;
> use Test::More;
>
> my $t = Test::Selenium::Remote::Driver->new;
> $t->get('https://en.wikipedia.org/wiki/Main_Page');
> $t->click_element_ok("//*[text()='Arts']",'clicked ok');
> $t->pause('2000');
> done_testing;
>
> ... and it is working.
>
> We introduced locators as parameters for functions relying on
find_element a while ago, so that users can specify a locator (xpath, css,
id, class ...) when using those functions.
> Normally, the locator should default to xpath when not specified (as
shown in my example), so the transition from the old parameter list to the
new one (with locator) should be seamless.
>
> Can you give an example of what you had that is not working ?
>
> As for the documentation, of course it should be updated, thank you for
the report <
https://ci3.googleusercontent.com/proxy/lhLVogFN-hhSRIB3fAZYM0xS45JVWb0izuEm9AjUeKKFB66lt-hLy0PjNR4ZTc47cfSiX2jcauToYcQwriVpETcpo3Sy2kO2U7iQ7_ihnNLSoK3ncvymHw=s0-d-e1-ft#https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png
>
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/-2nPAmtTIrTc0HCnaa-MQfUJsU-MeaSHNJPFEuK9sDVbltsohvKn1jQWn94N2YpcesHyQAgHsEQprNNErPcZgX28fuEIB__LGDPxojr-Wt7tH8s9ziIyiMmutg2dKlKKwLi80cWhEjx3QyugkgtjgTtmbMf4MA=s0-d-e1-ft#https://github.com/notifications/beacon/AH5UyPJyJQklbTJA4cMG32CzjJty2CUNks5oQenigaJpZM4E56Tz.gif
>

**Comment by peroumal1** [comment]
Even if with another finder, I manage to get it working : 

```perl 
use strict;
use warnings;
use Test::Selenium::Remote::Driver;
use Test::More;

my $t = Test::Selenium::Remote::Driver->new(default_finder => 'css','javascript' => 1);
$t->get('https://en.wikipedia.org/wiki/Main_Page');
$t->click_element_ok("a[title='Portal:Arts']",'clicked ok');
$t->pause('2000');
done_testing;
```

Can you try and modify my example above and give me a situation where it is not working ? 
Thanks.
