### ISSUE TITLE
Possible to send multiple keys simultaneously with send_keys (chord)?

### ISSUE THREAD

**Issue by mauritzhansen** [gempesaw/Selenium-Remote-Driver#216]
Is it possible to send multiple keys simultaneously with send_keys (or perhaps another way)? For instance, Ctrl + A.

I found the following on StackOverflow, but it does not seem to be implemented in the Perl interface:
http://stackoverflow.com/questions/11503736/key-press-in-ctrla-selenium-webdriver

Thanks

**Comment by peroumal1** [comment]
You can achieve that with the new [ActionChains](https://metacpan.org/pod/Selenium::ActionChains) class we added. It should be something like : 
```perl 
use Selenium::Remote::WDKeys 'KEYS'; 
use Selenium::Remote::Driver; 
use Selenium::ActionChains; 
my $driver = Selenium::Remote::Driver->new; 
my $action_chains = Selenium::ActionChains->new(driver => $driver); 
$action_chains->key_down([KEYS->{'control'}])
   ->send_keys('a')
   ->key_up([KEYS->{'control'}])->perform; 
```
It is quite similar to the Ruby implementation stated in the S/O question. 
I did not test the snippet above, tell me if it works for you. 
Cheers !

**Comment by gempesaw** [comment]
FWIW, the chains with `send_keys` didn't work for me on OS X, but putting the `a` in the first `key_down` arrayref did work for me. The following selects all the text on the page, and then opens a new tab as well. 

```perl
use strict;
use warnings;
use Selenium::Remote::WDKeys 'KEYS';
use Selenium::Remote::Driver;
use Selenium::ActionChains;

my $driver = Selenium::Remote::Driver->new;
$driver->get('https://www.perl.org');
$driver->find_element('body', 'tag_name')->click;

my $action_chains = Selenium::ActionChains->new(driver => $driver);

$action_chains->key_down([KEYS->{'command_meta'}, 'a'])
  ->key_up([KEYS->{'command_meta'}])->perform;
sleep(2); # for visual verification

$action_chains->key_down([KEYS->{'command_meta'}, 't'])
  ->key_up([KEYS->{'command_meta'}])->perform;
sleep(2); # for visual verification

$driver->quit;
```
