### ISSUE TITLE
get_ok test name doesn't work

### ISSUE THREAD

**Issue by skateamac** [gempesaw/Selenium-Remote-Driver#217]
Using version 0.26, setting test names works fine for every method I have tried except for get_ok.

code snippet:
```
$this->click_element_ok("Home", "link_text", "click Home link");
$this->body_text_contains("unit test","unit test string found");
print "about to run get_ok\n";
$this->get_ok($this->{browser_url},"Find ".$this->{browser_url}." site");  
print "ran get_ok\n";
```

output snippet:
```
ok 3 - click_ok'click Home link'
ok 4 - unit test string found
about to run get_ok
#     You named your test '1'.  You shouldn't use numbers for your test names.
#     Very confusing.
ok 5 - 1
ran get_ok
```

For now I just switched to using get() instead of get_ok().

Thanks for the great module.

**Comment by peroumal1** [comment]
Hello, 

I just tried the following snippet with S::R::D v0.26, perl 5.18.1 on Mac OS X Yosemite : 

```perl 
#! /usr/bin/perl
use strict;
use warnings;
use Test::Selenium::Remote::Driver;
use Test::More;
my $t = Test::Selenium::Remote::Driver->new();
$t->get_ok('https://en.wikipedia.org/wiki/Main_Page', 'get_ok WORKED');
done_testing;
```

It prints the following : 
```
ok 1 - get_ok WORKED
1..1
```

So... it could be multiple things : 

* can you give us your environment : OS, Perl version, mainly ?
* can you give us an example URL you are using ?

**Comment by skateamac** [comment]
I am using perl 5.20.2 on CentOS 5.11.  We are testing an intranet site so I can't give you that URL.
I'll try it on some other systems with older perl versions and respond back.

-Scott

**Comment by peroumal1** [comment]
Great ! 
I understand fully why you can't give the URL, but I asked just in case there is something specific about the URL (unusual parameters etc)... 
I'm going to try too with your perl version and see if anything unusual comes out.

**Comment by gempesaw** [comment]
huh, that's strange. any way that concatenation for the test name could end up equaling `1` through some weird implicit casting ? is that the exact code that generates that output ?

**Comment by skateamac** [comment]
If I remove the line 'use Test::More' from my package get_ok prints the
test name correctly without error.
We are upgrading from Selenium RC (Test::WWW::Selenium), and had needed
Test::More for capturing test output.
Looks like T::S::R::D already has that in the scope (via Test::LongString)
and I was reloading it afterward, probably caused some sort of namespace
collision.

Looks like I do not need it anymore.

Thanks.





On Tue, Jun 16, 2015 at 11:10 PM, Daniel Gempesaw <notifications@github.com>
wrote:

> huh, that's strange. any way that concatenation for the test name could
> end up equaling 1 through some weird implicit casting ? is that the exact
> code that generates that output ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gempesaw/Selenium-Remote-Driver/issues/217#issuecomment-112646767>
> .
>



-- 
-Scott

**Comment by peroumal1** [comment]
Cool !

I think you can avoid those kind of namespace collisions by using [namespace::clean](http://perladvent.org/2011/2011-12-03.html), but haven't tried it myself. 

Cheers !

**Comment by gempesaw** [comment]
hooray
