### ISSUE TITLE
get_page_source doesn't produce same output as manually pulling source from the browser

### ISSUE THREAD

**Issue by skateamac** [gempesaw/Selenium-Remote-Driver#223]
I noticed that if on page load, this jQuery code runs:
```    
$(window).load(function(){
    $('#date_created_label').html('');
});
```
S::R::D will not pull the original HTML for that 'date_created_label' when executing get_page_source().  
Instead, it shows the HTML after the jQuery / Javascript has run.

It would be better if S::R::D get_page_source matched the functionality of manually getting source from browser (using R-click, View Page Source in Firefox for example).  When you manually grab the source from the browser (after the page has loaded of course), the text for 'date_created_label' is still there in the source. I verified this on IE, FF, and Chrome.

Example output HTML segment from get_page_source():
`<td id="date_created_label" class="right" width="120" nowrap=""></td>`

Example output HTML segment from View Page Source in Firefox:
`<td id='date_created_label' class='right' width=120 nowrap>Creation Date :</td>`

We compare a baseline HTML file against the output of get_page_source, to quickly check expected page text is there.  Usually, we create a baseline HTML file via the manual browser method.  This is not a problem when using get_html_source() from WWW::Selenium (Selenium 1.0 RC). 

I am using perl 5.20.2 with S::R::D 0.25.  Server is: Selenium Server 2.46 / Chrome 43 (ChromeDriver 2.15) / Firefox 31 / IE 10 (32bit v2.46 driver).

**Comment by peroumal1** [comment]
Hello, 
I guess there are differences between Selenium RC and Selenium Webdriver, which leads to those kind of behaviours. 
More precisely, with Selenium Webdriver, you will always get the HTML content *after* JS execution. As it is how Selenium Webdriver is implemented, we cannot do anything on our side to fix this

Nevertheless, there are two possible alternatives : 

* use your browser with a proxy : the proxy will capture the traffic coming from/to the browser so you will be able to see the HTML file untouched 
* get directly the HTML you want by making a HTTP request with a HTTP client (`LWP`, `Mojo::UserAgent` ...)

Hope it helps !

**Comment by skateamac** [comment]
Thanks for the explanation and alternate options!
