### ISSUE TITLE
Multiple instances bound to different IPs on the same linux server.

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#227]
If I has x.x.x.1 and x.x.x.2 ip addresses bound on the same linux server, would it be possible to run an instance of selenium on x.x.x.1:4444 and another one on x.x.x.2:4444 and then use with Selenium-Remote-Driver? I know this is more of a selenium for linux question.. but I guess it's sort of relevant since I use this API.

**Comment by gempesaw** [comment]
That sounds like more of an issue for customizing the selenium server jar than anything having to do with this module. 

I'm not sure how to tell the selenium server to bind to a different IP address, but I'd guess that it should be possible? Perhaps there are java arguments that one could pass to the server jar during startup to choose the IP.

It might be easier to bind to different ports, actually, and it's about the same amount of complexity in the code to handle.

Alternatively, you could also go the route of Selenium Grid, and then there would be no changes in your code - in exchange for properly setting up & customizing the Grid, of course.

**Comment by freddyvega** [comment]
+1 on using grid2. This the easiest way when you are trying to distribute your tests to different IP/ports combinations.

**Comment by tranwave** [comment]
If I were to say have a selenium server without grid running and I connect with my perl client on x.x.x.6:4440 and another one on x.x.x.7:4440 but the server's main ip address is x.x.x.5 and if I connect to .6 or .7 would selenium reading with chrome read websites as .5 (the main server ip) or the ip that I'm connect to with the client such as .7?

**Comment by gempesaw** [comment]
> If I were to say have a selenium server without grid running and I connect with my perl client on x.x.x.6:4440 and another one on x.x.x.7:4440 but the server's main ip address is x.x.x.5 

It looks like the selenium server jar listens on all of the network adapters by default, so in theory if you have it running, you will be able to connect through any of its IPs, as per [this stackoverflow question](http://stackoverflow.com/questions/10607806/bind-selenium-to-a-specific-ip-possible) and some experimentation on my part. 

As for binding to a specific IP, it seems like you can do so in Hub mode (aka grid), but perhaps not necessarily so in the normal remote server mode. See [Hub.java](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/web/Hub.java#L83); I couldn't find a similar option in the [CLI arguments for the remote server](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/server/cli/RemoteControlLauncher.java), though

> would selenium reading with chrome read websites as .5 (the main server ip) or the ip that I'm connect to with the client such as .7?

no clue, perhaps try it out and see? I'm sort of curious why it matters - what is the end of goal of this ?

in addition to running servers on different ports, or using Grid, as already suggested, also, you may be able to use `iptables` to route the traffic more specifically.

**Comment by tranwave** [comment]
Well instead of changing IP with proxies. My ips are bound to the interface and lets say I want selenium to go to a test site on ip a and on a different test go to a test site on ip b instead of using these ips as proxies. So if I connected to selenium on ip a would it go to the site as ip a or whatever the default ip for that server is.

**Comment by gempesaw** [comment]
>  So if I connected to selenium on ip a would it go to the site as ip a or whatever the default ip for that server is.

Actually, now that you mention it, the two things you're asking about: 

- the IP used to access the selenium server 
- the network adapter that the browser itself uses to make requests

I would expect those to be completely unrelated, since the browser in question doesn't really know or care about what IP the selenium server is registered on ?

**Comment by tranwave** [comment]
Aaah so I guess the only way would be to use proxies.. Is there a chrome extra_capability to accomplish this I wonder..

**Comment by tranwave** [comment]
You can close this ticket.
