### ISSUE TITLE
Selenium::Chrome

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#228]
Does anyone know how to use Selenium::Chrome? I have the chromedriver running:
[root@localhost bin]# ./chromedriver
Starting ChromeDriver (v2.8.240825) on port 9515

and my code to connect is:
    try {
        $driver  = new Selenium::Chrome(
              'remote_server_addr'  => '127.0.0.1',
              'port'                => '9515',
        );
        return 1;
        $driver->quit();
    } catch {
        return 0;
    
    };

I get a 0 every time..

**Comment by gempesaw** [comment]
hm, Selenium::Chrome can start up its own `chromedriver` instance, if the binary can be found in your path. But, using it in the fashion you presented should also work; what is `$_` in your catch block - aka, the error message ?

**Comment by tranwave** [comment]
Sorry, just realized I have an older version of Selenium-Remote-Driver which doesn't have the module.

**Comment by gempesaw** [comment]
Hooray, problem solved :)
