### ISSUE TITLE
execute_script issue

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#229]
I'm using Selenium-Remote-Driver 0.17 and I'm getting an error when trying to execute the simple script:
                my $script = q{
                    window.stop();
                };
$driver->execute_script($script);

I get the following error:

Operation "==": no method found,
	left argument in overloaded package JSON::PP::Boolean,
	right argument in overloaded package JSON::PP::Boolean at /opt/ActivePerl-5.16/site/lib/Selenium/Remote/Driver.pm line 932.

**Comment by gempesaw** [comment]
What is on line 932 of your installation of Selenium Remote Driver ?

The error message is exactly the same as mentioned in #111 and solved in #148. If you can update to a newer version of S::R::D, I'd recommend that as a first step, as that will also make it significantly easier to debug.

If you can't update, (why not? I'm curious, perhaps we can solve that problem separately), try manually applying the fix merged in #148! That should probably solve the issue. Good luck.

**Comment by tranwave** [comment]
I can't upgrade yet because I encrypt/compile/encapsulate my code with  ActiveState PerlApp and as soon as I update it can't compile anymore. I've asked ActiveState what the problem was and they did not entirely know. They told me to do a couple things but I haven't gotten to it yet. I'll try #148. Thanks!

932 code block

sub javascript {
    my $self = shift;
932:    return $self->{javascript} == JSON::true;
}

**Comment by gempesaw** [comment]
> I can't upgrade yet because I encrypt/compile/encapsulate my code with ActiveState PerlApp and as soon as I update it can't compile anymore. I've asked ActiveState what the problem was and they did not entirely know.

ah, ok, I think you've mentioned that before and I forgot. well, thanks for the reminder :)

> I'll try #148. 932 code block

Okay, great, yeah, that block is what I expected. #148 fixes that exact line, closing this :)

**Comment by tranwave** [comment]
Is there a depository with all the older versions? I bet I'll still be able to compile with 0.18 which seems to fix the bug in the references you mentioned.

**Comment by tranwave** [comment]
Here's what I get when I run my application after compiling with perlapp after I update to Selenium-Remote-Driver 0.26:

Can't locate Selenium/Remote/Finders.pm in @INC (@INC contains:) at /</www/repustasis/bin/repustasisd>Module/Runtime.pm line 317, <DATA> line 1853.

**Comment by gempesaw** [comment]
Hmm, for old versions, they're probably all on metacpan, and backpan, although I don't have any links on hand from my phone. 

Alternatively, you can also get them from this repository

- if you want to use `dzil`, the master branch has tags for each release.
- without `dzil`, you can look at the `cpan` branch which has commits for each CPAN release; from those, you can do the usual `perl Makefile.PL` business.

The issue about finding Finders.pm seems like a quirk in the way the build was downloaded, as it's a dependency that is included in the package itself. 

Good luck! :)
