### ISSUE TITLE
Selenium::Chrome Remote

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#230]
Is it possible to use Selenium::Chrome to either execute a chromedriver binary on a remote server or talk to the chromedriver service running on a remote server? If so how would I do this. So far I can only get it to execute a local chromedriver binary and then talk to it.

When I start chromedriver it looks like it binds and runs as a server:
Starting ChromeDriver 2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281) on port 9515

**Comment by gempesaw** [comment]
> When I start chromedriver it looks like it binds and runs as a server:
Starting ChromeDriver 2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281) on port 9515

Yes, this is exactly what Selenium::Chrome does :) Selenium::Chrome was intended to make it easier to run on the local, current machine you're on, but it does so by manually executing the `chromedriver` binary, as you have said. For it to run remotely, you'd need to have permission to execute binaries on the remote machine, which isn't usually the case - seems like a security risk if other people have permission to execute binaries on my machine?

> Is it possible to use Selenium::Chrome to either execute a chromedriver binary on a remote server or talk to the chromedriver service running on a remote server?

If you're doing stuff remotely, does it make more sense to use Selenium::Remote::Driver as you've been doing ? 

I guess, if you're trying to avoid using the remote server `.jar`, hmm, you'd could install Chrome, chromedriver, and Selenium::Chrome on each remote machine that you want to use, and then do something like `ssh` into the machine and run the perl programs remotely...?

**Comment by tranwave** [comment]
Hmmm I like the thought security risk or not to run the binary remotely. I'm sure I could lock it down securely to a couple server that remotely access the chromedriver binary but how can this be done? Seems like Selenium:Chrome can only execute it locally.

**Comment by gempesaw** [comment]
> Seems like Selenium:Chrome can only execute it locally.

Yes, you're correct, there is a `system` command that is hardcoded in Selenium::CanStartBinary. It basically boils down to 

    /usr/local/bin/chromedriver --port=9515 --url-base=wd/hub

So, you'll have to figure out how to execute that command on your remote machine. Then, you can use `Selenium::Remote::Driver->new( 'remote_server_addr' => $your_remote_ip, port => 9515)`. 

The only difference between `Selenium::Chrome` and `Selenium::Remote::Driver` is that `Selenium::Chrome` extends S::R::D with the ability to start the `chromedriver` binary, and then automatically configures S::R::D to find & use the executable that it just started.

**Comment by tranwave** [comment]
Ok thank you! You can close this.
