### ISSUE TITLE
Page loading issues

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#231]
Is there any way to find an element while a page load icon is still spinning even though visually all the elements are loaded? I notice when using an ssl proxy that our test web site will load but the loading dial will spin and the S::R::D will wait until the loading is done to start finding an element. It takes forever this way. I had a similar ticket open earlier this year and someone told me to try javascript window.stop(). Not really a good idea. I'd rather poll the element some how while the page is still loading and if it's found then issue a window.stop() so I may proceed with manipulating the element. Is this possible? I guess I could issue a set_timeout('page load') to a low value like 10000 and then try catch a read timeout, look for the element and then refresh the page if it's not found and try again..

Does set_implicit_wait_timeout work while loading or after load? Does it mainly just work with find_element etc..?

Thanks!

**Comment by gempesaw** [comment]
> I guess I could issue a set_timeout('page load') to a low value like 10000 and then try catch a read timeout, look for the element and then refresh the page if it's not found and try again..

This is an good idea, although you may want to check for the element more than once before refreshing the page. Instead of doing the page load timeout to 10000, you could set the implicit wait timeout to  10000.

> Does set_implicit_wait_timeout work while loading or after load? Does it mainly just work with find_element etc..?

Yes, I'm pretty sure that the implicit wait timeout only changes the behaviour of find element.

**Comment by tranwave** [comment]
Thank you!
