### ISSUE TITLE
Proxy Username and Password

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#233]
We have a secure proxy ip we're using to test and by secure the proxy server lets you use the proxy if you know the username and password. I don't see a spot in the API where you can use a username and password for the proxy or is there something I'm missing?

**Comment by gempesaw** [comment]
Sorry, which proxy are you talking about - a proxy in front of the Selenium Server that your Perl code needs to communicate through, or a proxy in front of the webdriver browser ?
