### ISSUE TITLE
Set chrome binary location

### ISSUE THREAD

**Issue by tranwave** [gempesaw/Selenium-Remote-Driver#234]
Does anyone know the chrome option to set the chrome binary location? Right now I have this and it does not find the binary.

        $driver  = new Selenium::Remote::Driver(
            'browser_name'        => 'chrome',
            'remote_server_addr'  => $chromeNode->{'node_ip'},
            'port'                => $chromeNode->{'node_port'},
            'auto_close'          => 0,
            'extra_capabilities' => {'chromeOptions' => {'args' => ["--no-sandbox","binary=/usr/local/chromium47/chrome"]}});

I want to be able to do this without creating a google-chrome symbolic link in /usr/bin

**Comment by gempesaw** [comment]
https://sites.google.com/a/chromium.org/chromedriver/capabilities

It looks like it the `binary` thing should be a key in the `chromeOptions` hash, not in the `args` array:

```perl
{ 
    chromeOptions => {
        args => [ '--no-sandbox' ],
        binary => '/usr/local/chromium47/chrome'
    }
}
```

but I didn't test it out to make sure; good luck!

**Comment by tranwave** [comment]
Works! Thanks as always. I appreciate it.
