### ISSUE TITLE
move_to does not change mouse pointer position

### ISSUE THREAD

**Issue by davewood** [gempesaw/Selenium-Remote-Driver#235]
$driver->move_to(element => $playlist, xoffset => 5, yoffset => 5);
    $driver->button_down;
    my $playlist_song_container = $driver->find_element('mox-playlist-songs', 'tag_name');
    $driver->move_to(element => $playlist_song_container, xoffset => 5, yoffset => 5);
    $driver->button_up;

the pointer icon changes when the button_down() line is executed. but the mouse position never changes.

REQ: POST, session/7bfa5f1f-1831-4b13-8207-049aa984d1b9/moveto, {"yoffset":5,"element":"{c7f9a78e-ec42-4eeb-8705-d2d7c0af386e}","xoffset":5}
RES: {"name":"mouseMoveTo","sessionId":"7bfa5f1f-1831-4b13-8207-049aa984d1b9","status":0,"value":{"message":"ok"}}
REQ: POST, session/7bfa5f1f-1831-4b13-8207-049aa984d1b9/buttondown, {}
RES: {"name":"mouseButtonDown","sessionId":"7bfa5f1f-1831-4b13-8207-049aa984d1b9","status":0,"value":{"message":"ok"}}
REQ: POST, session/7bfa5f1f-1831-4b13-8207-049aa984d1b9/element, {"using":"tag name","value":"mox-playlist-songs"}
RES: {"name":"findElement","sessionId":"7bfa5f1f-1831-4b13-8207-049aa984d1b9","status":0,"value":{"ELEMENT":"{8267fcb2-b0c6-4392-adb4-c0920c6d65e9}"}}
REQ: POST, session/7bfa5f1f-1831-4b13-8207-049aa984d1b9/moveto, {"yoffset":5,"element":"{8267fcb2-b0c6-4392-adb4-c0920c6d65e9}","xoffset":5}
RES: {"name":"mouseMoveTo","sessionId":"7bfa5f1f-1831-4b13-8207-049aa984d1b9","status":0,"value":{"message":"ok"}}
REQ: POST, session/7bfa5f1f-1831-4b13-8207-049aa984d1b9/buttonup, {}
RES: {"name":"mouseButtonUp","sessionId":"7bfa5f1f-1831-4b13-8207-049aa984d1b9","status":0,"value":{"message":"ok"}}

Mozilla Iceweasel 38.4.0
Selenium::Remote::Driver 0.27.

ps: If I do not provide an element the mouse location doesnt change relatively to its current position either.

**Comment by davewood** [comment]
I also tried action chains but dont get a change in the mouse position either.

stupid question since i have no experience with selenium. when i run a selenium test the actual mouse pointer moves, right? or is the movement hidden from my mouse pointer and the browser only receives events that I cannot actually see?

    use Selenium::ActionChains;
    my $chain = Selenium::ActionChains->new(driver => $driver);
    $chain->click_and_hold($playlist);
    my $playlist_song_container = $driver->find_element('mox-playlist-songs', 'tag_name');
    $chain->move_to_element_with_offset($playlist_song_container,5,5);
    $chain->release($playlist);

**Comment by freddyvega** [comment]
When I do a move_to the element is scrolled into view. The windows mouse pointer is under the control of the OS and not webdriver hence it doesn't move.


At this point though, you should be able to interact with the element. What is it you're trying to do with this element?






On Mon, Nov 23, 2015 at 4:48 AM -0800, "David Schmidt" <notifications@github.com> wrote:





I also tried action chains but dont get a change in the mouse position either.

stupid question since i have no experience with selenium. when i run a selenium test the actual mouse pointer moves, right? or is the movement hidden from my mouse pointer and the browser only receives events that I cannot actually see?

    use Selenium::ActionChains;
    my $chain = Selenium::ActionChains->new(driver => $driver);
    $chain->click_and_hold($playlist);
    my $playlist_song_container = $driver->find_element('mox-playlist-songs', 'tag_name');
    $chain->move_to_element_with_offset($playlist_song_container,5,5);
    $chain->release($playlist);


---

**Comment by davewood** [comment]
I am trying to  drag and drop an element.

**Comment by peroumal1** [comment]
Hello,

If drag and drop is what you are trying to accomplish, it certainly won't
work with Selenium, but there are workarounds.

I suggest you to have a look at this :
http://stackoverflow.com/questions/29381233/how-to-simulate-html5-drag-and-drop-in-selenium-webdriver
and see if it helps you.

Regards,

On Mon, Nov 23, 2015 at 1:56 PM, David Schmidt <notifications@github.com>
wrote:

> I am trying to drag and drop an element.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gempesaw/Selenium-Remote-Driver/issues/235#issuecomment-158926379>
> .
>



-- 
Peroumalnaik Emmanuel
