### ISSUE TITLE
difference between set_implicit_wait_timeout and set_timeout('implicit',...)

### ISSUE THREAD

**Issue by rol1** [gempesaw/Selenium-Remote-Driver#237]
Hi,

can you improove the documentation to be more clear about  "set_implicit_wait_timeout" and "set_timeout('implicit',...)". I'm not shure about the difference between this functions.

Thank you very much

Roland

**Comment by freddyvega** [comment]
From what I can see, set_implicit_wait_timeout executes the command 'setImplicitWaitTimeout' which ultimately POSTs `/session/:sessionId/timeouts/implicit_wait`

while set_timeout executes the command 'setTimeout which POSTs `/session/:sessionId/timeouts`

So the difference seems to be implicit vs explicit type of time out. With the latter being used to explicitly and temporarily modify an 'implicit' timeout.

**Comment by freddyvega** [comment]
I dug into the code without checking the docs. I just checked the docs and saw that it pretty much says the same thing there. Which part of the documentation would you like to see improved? Can you give an example?

**Comment by rol1** [comment]
Hi,

sorry, but i can't give you an example, i stucked also while reading the doc's.

THX

Roland

**Comment by freddyvega** [comment]
What about the explanation I just gave you? That didn't help?

**Comment by rol1** [comment]
not realy, the setImplicitWaitTimeout part was ok, but what if i use "implicit" as first parameter to set_timeout.
I guess it's the same, but i don't think so, because i believe that no one writes two functions whicht do the same.

**Comment by freddyvega** [comment]
the difference seems to be implicit vs explicit type of time out. With the latter being used to explicitly and temporarily modify an 'implicit' timeout.

**Comment by rol1** [comment]
Shure?
I guess the timeout will last, until i set it to a different value, independent from the function i use to set it. Or do you mean anything else with "temporary"?

**Comment by freddyvega** [comment]
Yes.

https://code.google.com/p/selenium/wiki/JsonWireProtocol#POST_/session/:sessionId/timeouts

**Comment by rol1** [comment]
As far as i understand the doc's on the page you send, it's equal, but i'm not a developer, and english is not my mother tongue.
If so, this should be clearly written in the Selenium::Remote::Driver docs. Maybe the "set_implicit_wait_timeout" funktion could be marked as deprecated.

**Comment by freddyvega** [comment]
Can try to describe what it is you are trying to do, this way I can give you an idea how to go about doing it?

**Comment by rol1** [comment]
I had to increase timeouts, because the webserver i was working with was reacting ver very slow. Therefore i looked at the docs and found both functions, but i was confused which one would be the right one.

**Comment by freddyvega** [comment]
Ok, well you can choose whichever one you want. They both ultimately lead to the same place: an implicit timeout being set. (implicit means the amount of time webdriver will wait for an element to become available until it returns).

Hope that helps.

**Comment by rol1** [comment]
Yes it helps.

**Comment by freddyvega** [comment]
But if I were you, I'd be more interested in why the server is slowing down rather than trying to slow down my scripts. That's a suggestion.

In other words is your server slowing down when you run the scripts? Or is it due to heavy access? Is this a test server? What does your process list / memory utilization / etc say? These would all be things I'll be looking for when I see a "slow down" in server performance.

**Comment by rol1** [comment]
Your right, but i know the answer. The load balancer was miss configured, so all trafic hit one server. But it took a while, till the admins found it, so i increased the timeout in the meanwhile :-)

**Comment by freddyvega** [comment]
Ah I see. Well depending how you set the time out it will be good for you to know that the implicit timeout is set 0 by default if you don't set it to anything explicitly (as in with set_timeout(implicit) or set_implicit_wait_time_out(ms)).
