### ISSUE TITLE
Firefox 43.0 doesn't start - please update webdriver.xpi to 2.48.0

### ISSUE THREAD

**Issue by andyjack** [gempesaw/Selenium-Remote-Driver#238]
`Unable to connect to the /usr/bin/firefox binary on port 9090`

I think this is due to the unsigned .xpi (selenium 2.45.0) not being loaded by firefox 43, please see https://github.com/SeleniumHQ/selenium/issues/1385

**Comment by gempesaw** [comment]
oh! the linked issue is very helpful, looks like this should be a straightforward fix. I'll take a look

**Comment by gempesaw** [comment]
Ok, I've got the fix ready in another branch, I plan to get it out in a day or two. In the meantime, creating a custom Selenium::Firefox::Profile with the [boolean_preference](https://metacpan.org/pod/Selenium::Firefox::Profile#set_boolean_preference) `"xpinstall.signatures.required": 0` may tide you over.
