### ISSUE TITLE
send_keys sometime didn't work

### ISSUE THREAD

**Issue by autodataming** [gempesaw/Selenium-Remote-Driver#243]
```Perl
$subtext_elm=wait_until{$driver->find_element_by_id("substanceIds")};	
$subtext_elm->clear();
	$subtext_elm->send_keys($casid);
```
some time (very less) ,it will didn't send_keys,
and I will try to adopt the follow code, can you have a good choice?
```Perl
$subtext_elm=wait_until{$driver->find_element_by_id("substanceIds")};
	$subtext_elm->clear();
	$subtext_elm->send_keys($casid);
	while(1)
	{
	   if($subtext_elm->get_value() eq $casid)
	   {
	      last;	
	   }
	   else
	   {
	   		$subtext_elm->clear();
	        $subtext_elm->send_keys($casid);
	   }	
		
	}
```

**Comment by gempesaw** [comment]
> some time (very less) ,it will didn't send_keys,

when send_keys doesn't work, is there an error in the webdriver console? that would probably be the most help in debugging this. 

> and I will try to adopt the follow code, can you have a good choice?

that code seems logically correct, does it not work ?
