### ISSUE TITLE
run a loop,it come across problem

### ISSUE THREAD

**Issue by autodataming** [gempesaw/Selenium-Remote-Driver#245]
Error while executing command: findElements: An unknown server-side error occurred while processing the command.: Error communicating with the remote browser. It may have died.
```Perl
while(<FH>)
{
$driver->find_elemnt();
...
$webelm->click();
}
```
It always die after some cycles.

**Comment by gempesaw** [comment]
> Error communicating with the remote browser. It may have died.

This usually means that the webdriver browser closed, for whatever reason. Without more information about the app under test and the full test script, it's very difficult to debug.
