### ISSUE TITLE
how to convert the driver to the LWP useragent?

### ISSUE THREAD

**Issue by autodataming** [gempesaw/Selenium-Remote-Driver#246]
https://metacpan.org/pod/LWP::UserAgent
https://metacpan.org/pod/Selenium::Remote::Driver

how to convert the Selenium::Remote::Driver to theLWP::UserAgent?

**Comment by gempesaw** [comment]
Sorry, I don't understand your question. Can you try to explain what you're trying to do ?

FWIW, S::R::D uses LWP::UserAgent to send its HTTP requests. But, on its own, LWP::UserAgent doesn't know anything about the Webdriver JSONWireProtocol API, or about the data structures that webdriver returns, of course.  The two modules are for two completely different purposes, converting between them doesn't make sense. Perhaps you're looking for a different word ?

**Comment by autodataming** [comment]
You must login in some website, then you can do something ,download the information from the website.

when I analysed the login POST process, the password was encrypted by the JS script. 
To login in will be very easy if I can do it by selenium. Then to POST or GET something by the useragent.

**Comment by gempesaw** [comment]
Ah, I see. Unfortunately, the cookies and session data that you're interested in are not stored in Selenium::Remote::Driver anywhere. The session data only exists in the browser, and _not_ in the Perl code. 

So, you have a few options, perhaps. 

1. log in with the browser, and then use `get_cookie` or custom javascript via `execute_script` to make the browser tell you the authorization information that it has

2. use a proxy like [Browsermob::Proxy](https://metacpan.org/pod/Browsermob::Proxy) to MITM your test traffic, and then parse out the authorization information from your own network requests

3. reverse engineer the JS encryption for the password and do it entirely on the perl side? this one may be impractical :(

**Comment by autodataming** [comment]
Thank you very much.
