### ISSUE TITLE
Unable to send_keys to an element

### ISSUE THREAD

**Issue by moezhirani** [gempesaw/Selenium-Remote-Driver#247]
Here is the scenario I am trying to execute:

1) I click an 'edit' button on a webpage
2) It results in a dialog box that contains two input fields (both are text fields , but one of them can be filled with a datepicker. You could also manually type in the date)
3) In automation, it would be rather cumbersome to use the datepicker; so , instead I want to type in the date manually. So I use a send_keys_to_element call to do it. However, I get the following error:

```perl
[ERROR] [9554] [Wed Jan 20 14:08:19 2016] <T2::Page 518> (devVM) Error while executing command: An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element).: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=47.0.2526.111)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: '6CP9BW1', ip: '10.237.252.119', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_31'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\hirani\AppData\Local\Temp\scoped_dir4204_17307}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=47.0.2526.111, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 9316e6b64813ff86da50c679ef873c72 at (eval 3020)[/home/autotest/local-lib/lib/perl5/Sub/Quote.pm:5] line 17.
```

I am not sure why the element is in an 'invalid' state. I thought the datepicker may be interfering ; so, I simulated hitting the 'escape' key by using the send_keys_to_active_element call , which makes the datepicker disappear before i attempt to type in the date. However, the same error appears.

Whats even more intriguing is that this test worked about a month ago without issue. I am not certain why this is failing.
![element is inactive error](https://cloud.githubusercontent.com/assets/1643674/12460191/95691d94-bf80-11e5-931c-4f6bd4215c10.png)

**Comment by gempesaw** [comment]
Aw, this looks like a tough problem to pin down without an example HTML snippet to debug against. I can really only guess, but I'm not sure it'll help much. 

Are you sure you've selected the correct element? A common UI trick is to hide the literal `<input>` and replace it with a `<span>` or `<div>` whose behavior and styling may be easier to control. Although, this test having worked in the past kind of goes against that theory. 

Unfortunately, without an example HTML snippet, I'm not sure I can be of much assistance :(
