### ISSUE TITLE
firefox_profile and preference permissions.default.image

### ISSUE THREAD

**Issue by vkatsikaros** [gempesaw/Selenium-Remote-Driver#248]
Hi

I tried to disable image downloading for Firefox (1) using a `Selenium::Firefox::Profile`, and failed. I used the latest `0.2701` (includes fix for #239).

In the example I set several values to `permissions.default.image` preference, but the screenshots always contains images.

```
#! /usr/bin/perl

use strict;
use warnings;
use feature qw/say/;

use Selenium::Firefox;
use Selenium::Firefox::Profile;

say $Selenium::Firefox::VERSION;
say $Selenium::Firefox::Profile::VERSION;

foreach my $i (0..3)
{
	my $screenshot_file;
	my $profile = Selenium::Firefox::Profile->new;
	$profile->set_preference(
		'permissions.default.image'    => $i,
	);
	say "permissions.default.image: " . $profile->get_preference('permissions.default.image');
	my $driver = Selenium::Firefox->new(
		firefox_profile => $profile,
	);

	say "GET google";
	$driver->get( "https://www.google.com/search?q=london" );
	$screenshot_file = "image-google$i.png";
	$driver->capture_screenshot( $screenshot_file );

	say "GET telegraph";	
	$driver->get( "http://www.telegraph.co.uk/" );
	$screenshot_file = "image-telegraph$i.png";
	$driver->capture_screenshot( $screenshot_file );
}
``` 

To doublecheck that profile setting works I tried this (borrowed from #202 ) which works fine:
```
#! /usr/bin/perl

use strict;
use warnings;

use feature qw/say/;
use Selenium::Firefox;
use Selenium::Firefox::Profile;

my $profile = Selenium::Firefox::Profile->new;
$profile->set_preference(
    'general.useragent.override' => 'our custom user agent!'
);

my $firefox = Selenium::Firefox->new(
	firefox_profile => $profile,
);

$firefox->get('http://whatsmyuseragent.com/');
say $firefox->find_element_by_class('info')->get_text;

say $Selenium::Firefox::Profile::VERSION;
say $Selenium::Remote::Driver::VERSION;
```

To rule out a bug in Firefox 43.0.4, I manually changed the preference to `2` from `about:config` and after restarting the browser indeed it stopped loading images.

(1) 
```
$ firefox --version
Mozilla Firefox 43.0.4

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

**Comment by gempesaw** [comment]
Ah yes, for some [reasons](http://stackoverflow.com/a/31572457/1156644), Firefox does not respect `permissions.default.image` and will overwrite it regardless of what we pass in during driver instantiation. This impacts the binary startup as well as if we were using the standalone server jar.

There is a [workaround](http://stackoverflow.com/a/34161948/1156644) (but I don't know _why_ it works like this) where if you also set `browser.migration.version` high enough, then Firefox will respect `permissions.default.image`. 

```perl
use strict;
use warnings;
use Selenium::Firefox;
use Selenium::Firefox::Profile;

my $profile = Selenium::Firefox::Profile->new;

# permissions.default.image options http://kb.mozillazine.org/Permissions.default.image
# 1 - load images (default)
# 2 - never load images
# 3 - prevent 3rd party images from loading
my $NEVER_LOAD_IMAGES = '2';

# arbitrary number larger than default browser.migration.version
# (currently set to 31 on my computer, check at about:config). Setting this to a number
# larger than the current one prevents Firefox from overwriting the
# default.image setting on startup for some reason
my $FORCE_RESPECT_DEFAULT_IMAGE = 9999;

$profile->set_preference(
    'permissions.default.image' => $NEVER_LOAD_IMAGES,
    'browser.migration.version' => $FORCE_RESPECT_DEFAULT_IMAGE
);

my $firefox = Selenium::Firefox->new(firefox_profile => $profile);
```

**Comment by vkatsikaros** [comment]
@gempesaw you are right :( I should have tested better, by loading custom profile instead of changing this through the UI!

If I launch firefox with `firefox --profile <TEST_DIR>` and in `TEST_DIR` I use the following for  `prefs.js`:
```
user_pref("permissions.default.image", 2);
user_pref("lala.lala", "lala");
```
then in `about:config` my test preference is set to `lala`, but `permissions.default.image` remains 1.

Thanks for the weird workaround.

**Comment by vkatsikaros** [comment]
Hi again. I couldn't find any documentation for the "frozen" firefox preferences, so I opened [this bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1249908). However, the devs there say that the way we reproduce the bug is `off the supported path`. 

So, could it be something is missing (firefox-wise) when the profile is created in this way?

**Comment by gempesaw** [comment]
@vkatsikaros From reading that thread, I _think_ what they meant about the supported path was editing `prefs.js` by hand, vs setting up a `user.js` with our preferences in it. FWIW, these Perl bindings set up Firefox the same way that the rest of the webdriver bindings do (ruby/python/js), via user.js.
