### ISSUE TITLE
Specifying the path for the chromedriver.log file when using Selenium::Chrome

### ISSUE THREAD

**Issue by Qarj** [gempesaw/Selenium-Remote-Driver#252]
I'm getting "No such session" errors from chromedriver.exe which seem random. In an effort to try and debug this, I need to see the chromedriver.log file.

I'm starting the Selenium session as follows:

```
                    $driver = Selenium::Chrome->new (
                                                  binary => 'C:\ChromeDriver\chromedriver.exe',
                                                 _binary_args => '--log-path=chromedriver.log',
                                                 'browser_name' => 'chrome'
                                                 );
```

When I do this execution pauses and Windows pops up with an error message:

Title Bar: `C:/ChromeDriver/chromedriver.exe--log-path=chromedriver.log`

Message `Windows cannot find 'C:/ChromeDriver/chromedriver.exe--log-path=chromedriver.log'. Make sure you typed the name correctly, and then try again.`

Putting a space before the --log-path does not help. In this scenario chromedriver.exe appears to crash without returning a message.

Ideally I would also like to specify --verbose too.

I'm not sure how to go about this. Is _binary_args for internal use only?

**Comment by gempesaw** [comment]
Hm, `_binary_args` is used to set up the appropriate port and the proper webdriver context.

```perl
has '_binary_args' => (
    is => 'lazy',
    builder => sub {
        my ($self) = @_;

        my $context = $self->wd_context_prefix;
        $context =~ s{^/}{};

        return ' --port=' . $self->port . ' --url-base=' . $context . ' ';
    }
);
```

Putting the space lets `chromedriver.exe` start up properly, but without the proper port and context `/wd/hub/`, S::R::D isn't able to communicate with the chromedriver server to start up a Chrome instance, so the whole thing crashes after some timeout. 

The default behavior for Chrome.pm is to look for an open port starting at 9515 and incrementing upwards until one is found. I think, in the current situation, you can use `_binary_args` for your own if you decide on a port beforehand and pass it as well in `_binary_args` in addition to the arguments you want to add. So, something like

```perl
# untested
my $port = 9515;
my $chrome = Selenium::Chrome->new(
    port => $port,
    _binary_args => " --port=$port --url-base=/wd/hub --log-path=chromedriver.log"
);


But, having to choose the port manually is a bit of pain, we probably do need to add a proper way of specifying options to the chromedriver.exe binary that doesn't overwrite the necessary arguments that we build in `_binary_args`. 

Oh, you may also be able to specify the chromedriver log in the desiredCapabilities hash.

**Comment by Qarj** [comment]
Thanks very much, your code worked perfectly!

I don't mind having to manage the port number myself, I found some code on PerlMonks for checking if a port is in use or not.

Maybe there could be a binary_extra_args parameter that just gets appended to _binary_args.
