### ISSUE TITLE
How to get a css element with Selenium using a css framework like DevBuilder and coding in Perl 

### ISSUE THREAD

**Issue by Chaoui05** [gempesaw/Selenium-Remote-Driver#262]
My issue is in the title !

Thanks to everybody  !!

**Comment by gempesaw** [comment]
Sorry, I'm not familiar with DevBuilder. Still, regardless of CSS framework, nothing really changes - you need to choose an element locator type (common ones are using CSS selectors or xPath selectors), and then use an appropriate locator that corresponds to the element you wish to interact with.

Without a more specific example (HTML of the page you're trying to interact with and the Perl script you're using to manipulate the page) there's not much we can do to help.
