### ISSUE TITLE
Selenium::Waiter waits $args{interval} seconds, even on success

### ISSUE THREAD

**Issue by ehuelsmann** [gempesaw/Selenium-Remote-Driver#272]
As documented in its [CAVEATS section](http://search.cpan.org/~ether/Try-Tiny-0.24/lib/Try/Tiny.pm#CAVEATS), "return" returns from the 'try' block, not the outer function.

This means that https://github.com/gempesaw/Selenium-Remote-Driver/blob/master/lib/Selenium/Waiter.pm#L92 does not return from ```wait_until```. As a result, the ```finally``` clause  will always execute. Since the only purpose of that clause is to sleep, the sleep is performed even on success.

**Comment by gempesaw** [comment]
Oh, cool! Thanks for the heads up.
