### ISSUE TITLE
Orientation Commands for windows device

### ISSUE THREAD

**Issue by padmaja2812** [gempesaw/Selenium-Remote-Driver#287]
Hi
I am using winium to automate winphone8.1 application.
Facing issues with orientation as there is no function exposed  for getOrienttion and setOrientation.
these actions are implemented in inner and outer server.
Is there any other workout to achieve this task.

Thanks
Padmaja

**Comment by gempesaw** [comment]
Hi Padmaja! I don't know what winium is - presumably it is [this other project](https://github.com/2gis/Winium)? This repository is for the Perl bindings to the Webdriver server, not for Winium and not typically for phone applications, as far as I'm aware. Perhaps try your issue over at the [winium issues tracker](https://github.com/2gis/Winium/issues)? Good luck!

**Comment by padmaja2812** [comment]
Hi Gem,
I got the solutions from other forum.Sorry for inconvenience.

Thanks
Padmaja
