### ISSUE TITLE
LWP timeout

### ISSUE THREAD

**Issue by zdm** [gempesaw/Selenium-Remote-Driver#295]
Hi.
You are using LWP that has default timeout 180 seconds.
When I am running async script, that can run more than 180 secs, LWP drops connection on timeout.
Currently I am using patch for Selenium::Remote::Driver:

```
has 'ua' => (
    is      => 'lazy',
    builder => sub { my $ua = LWP::UserAgent->new; $ua->timeout(100000); return $ua; }
);
```

Is it possible to set LWP timeout to the largest number or sync LWP timeout value with async_script_timeout value?

**Comment by zdm** [comment]
LWP::UserAgent timeout must be not lower, than largest script, implicit, page load or async_script timeout.

**Comment by gempesaw** [comment]
It feels odd to me to automatically set the LWP::UserAgent timeout. Is there an issue with setting it manually?

```perl
my $timeout_ua = LWP::UserAgent->new;
$ua->timeout(100000);
my $d = Selenium::Remote::Driver->new( ua => $ua );
```

That `ua` should get passed all the way in to [RemoteConnection](https://github.com/gempesaw/Selenium-Remote-Driver/blob/c71530b82098f5d2bece18cc61dc7de6e6b777fd/lib/Selenium/Remote/Driver.pm#L389) and lets you manage it manually, right? Or is that behavior not what you see?

**Comment by zdm** [comment]
Ok, no problem,
I can set it manually.

**Comment by gempesaw** [comment]
What I probably need to do, though is to add some documentation to that effect to help future users. Thanks!

**Comment by mjegh** [comment]
```
WARN [4] Failed to create selenium remote driver - Could not create new session: chrome not reachable  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-30-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.05 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'feed-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-30-generic', java.version: '1.7.0_95'
Driver info: org.openqa.selenium.chrome.ChromeDriver at xx.pl line 149.
 END

TIME WAS 63
```

So it looks like it times out in 60s. I cannot afford to leave chomes around so I guess I'll have to try your trick to increase the timeout and see where gets me. I'd prefer to abort more quickly but not leave the chome around.
