### ISSUE TITLE
switch_to_window() error

### ISSUE THREAD

**Issue by lingvik** [gempesaw/Selenium-Remote-Driver#301]
Hello there.
I'm referring to Selenium::Remote::Driver version 1.02.

The function **switch_to_window()** is sending a parameter **name**, but the correct parameter is **handle**.
In file `/lib/Selenium/Remote/Driver.pm`, line 828:
`my $params = { 'name'    => $name };`

should be changed to:
`my $params = { 'handle'    => $name };`

Source: [WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html#switch-to-window)

EDIT: I see I did not do a particularly good job yesterday at night. Here's a bit more information.
I'm using geckodriver - I tried versions 0.9.0 and newer. The error was crashing my program - geckodriver returned an error and Selenium::Remote::Driver croaked. After I applied the change locally, it worked.

**Comment by gempesaw** [comment]
Cool, thanks for the information. I'll get a fix in shortly c:
