### ISSUE TITLE
v1.0.2 breaks testing with Sauce Labs

### ISSUE THREAD

**Issue by ehuelsmann** [gempesaw/Selenium-Remote-Driver#302]
See for more information: https://travis-ci.org/ehuelsmann/LedgerSMB/jobs/196420519#L1604

The immediate error is:
```
xt/65-sauce.t ............... 1/2 coercion for "id" failed: When passing in an object to the WebElement id attribute, it must have at least one of the ELEMENT or element-6066-11e4-a52e-4f735466cecf keys. at /home/travis/locallib/lib/perl5/Selenium/Remote/Driver.pm line 957.
```

Which isn't too helpful, but the source of the error is https://github.com/gempesaw/Selenium-Remote-Driver/blob/master/lib/Selenium/Remote/WebElement.pm#L80 which was added/changed in https://github.com/gempesaw/Selenium-Remote-Driver/commit/67eff3da5069e5fdb047b482702a37d293db2422 with this commit message:

```
The spec has a different key name in the response to find_element for
the JSON element object: https://www.w3.org/TR/webdriver/#elements

We want to handle both cases, because the SRD driver jar still uses the
old format, but in theory in the future all of the drivers and the SRD
shoul conform to the spec.
```

**Comment by gempesaw** [comment]
Huh, that's unexpected. Thanks for the heads up, I'll take a look tomorrow.

**Comment by gempesaw** [comment]
@ehuelsmann oh hey, are the sauce lab runs public? If so, can you send me a link to an example saucelabs job that failed ? I'm curious about the selenium console output during the run. If not, that's okay, I can also probably just reproduce on my own...

**Comment by ehuelsmann** [comment]
@gempesaw had to find out which link coincides with the test script. This is the (supposedly public) link of the SauceLabs dashboard for that test: https://saucelabs.com/beta/tests/ecaf4e4a37d04d3fbb423fa6240bff16/metadata#5

A production installation of the pages tested in the test script are development versions of respectively https://demo.cloud.efficito.com/erp/1.5/login.pl and https://demo.cloud.efficito.com/erp/1.5/setup.pl

**Comment by gempesaw** [comment]
Hmmm, one of the from the saucelabs job you sent has this:

```
[4.131][INFO]: COMMAND FindElement {
   "using": "name",
   "value": "s_passwd"
}
[4.131][INFO]: Waiting for pending navigations...
[4.131][INFO]: Done waiting for pending navigations
[4.157][INFO]: Waiting for pending navigations...
[4.158][INFO]: Done waiting for pending navigations
[4.158][INFO]: RESPONSE FindElement no such element: Unable to locate element: {"method":"name","selector":"s_passwd"}
  (Session info: chrome=46.0.2490.71)
```

Is that the expected behavior of the test? I didn't get a chance to look at login.pl or setup.pl yet. And,  I also need to look into why the error message was not nearly as helpful as it could've been...

**Comment by ehuelsmann** [comment]
@gempesaw the script that was used for the Selenium session is here: https://github.com/ehuelsmann/LedgerSMB/blob/master/xt/65-sauce.t

There's a script which does roughly the same thing (but against `phantomjs` in my case, or against a Selenium cluster in other cases), but does not fail. It's the script preceeding the failing one in the Travis CI transcript linked above.

**Comment by gempesaw** [comment]
![image](https://cloud.githubusercontent.com/assets/1437272/22527770/65130f86-e89e-11e6-8bf4-5f0d8a8b4fe4.png)


From the master branch of LedgerSMB, looking at 65-sauce.t, the test is going to setup.pl, and then searching for `s_passwd`. So I opened up the demo setup.pl page you linked, and I don't see an element that matches that locator on the page (see screenshot). I do see an element that matches [name="password"], though. This might explain the error message found in the Selenium webdriver logs.

But, am I debugging this incorrectly? Perhaps I was reading the wrong branch of LedgerSMB? Or, the demo setup.pl page that you helpfully linked to above doesn't have the latest version of the code?

**Comment by ehuelsmann** [comment]
@gempesaw That is embarrassing! You're completely right.

There is however the problem that we ran tests for more than a year with older versions of Selenium::Remote::Driver which didn't complain about this naming mismatch -- which was the basis of this report.
Any idea from the older release code why this would have been a problem?

(other than that, I don't think there's anything to be reported anymore...)

**Comment by gempesaw** [comment]
Yeah, uhh, I have no idea how it was working before :P but, glad things are sorted!

https://travis-ci.org/ledgersmb/LedgerSMB/jobs/197642213

c:
