### ISSUE TITLE
Geckodriver v0.14 does'nt work with FF 48.0 & 51.0.1

### ISSUE THREAD

**Issue by GeoffroyB** [gempesaw/Selenium-Remote-Driver#308]
Hi,

When I try to find an element by name with simple firefox driver:

```
use Test::Selenium::Firefox;
my $test_driver = Test::Selenium::Firefox->new;
$test_driver->get_ok('https://duckduckgo.com', "Browser can load page");
$test_driver->find_element_ok('q','name');
$test_driver->quit();
```

 I have the error message:

>Use of uninitialized value in hash element at E:/perls/Strawberry/perl/site/lib/Selenium/Remote/ErrorHandler.pm line 126.
> Test::Selenium::Firefox=HASH(0x451fb88)Error while executing command: findElement at E:/perls/Strawberry/perl/site/lib/Selenium/Remote/Driver.pm line 313.

Can this problem be fixed?

Thanks you very much.

PS: For your information, when I use: Test::Selenium::Remote::Driver->new(browser_name => 'firefox') OR Test::Selenium::InternetExplorer->new, I have an other error message:
>Selenium server did not return proper status at E:/dev/myprogram/local/lib/perl5/Selenium/Remote/Driver.pm line 401.

**Comment by gempesaw** [comment]
FWIW, one of the issues here is that geckodriver doesn't support `name` as a finder (previously #299). I've added a conversion when using `name` to use `css` and `[name=$query]` instead, which should do the same thing, but the problem can be avoided all together by not using the `name` method for finding elements when using geckodriver. 

When using the standalone server, it already takes care of this conversion.

> Selenium server did not return proper status at E:/dev/myprogram/local/lib/perl5/Selenium/Remote/Driver.pm line 401.

This indicates that the selenium server isn't running - the default location is localhost:4444. Anyway, the changes in 9a57539 should make it out to cpan as part of version 1.20 of S::R::D once they pass their tests. Thanks and sorry for the delay :p

**Comment by davewood** [comment]
this might be related.

S::FF 1.20
geckodriver 0.19.1
FF  52.5.0 (64-bit)

```
my $driver = Selenium::Firefox->new;
$driver->get($url);
$driver->shutdown_binary;
```

```
perl selenium.pl 
Use of uninitialized value in hash element at /home/david/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Selenium/Remote/ErrorHandler.pm line 126.
Error while executing command: quit: quit at /home/david/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Selenium/Remote/Driver.pm line 327.
 at /home/david/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Selenium/Remote/Driver.pm line 327.
Use of uninitialized value in hash element at /home/david/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Selenium/Remote/ErrorHandler.pm line 126.
	(in cleanup) Error while executing command: quit: quit at /home/david/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Selenium/Remote/Driver.pm line 327.
 at /home/david/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Selenium/Remote/Driver.pm line 327.
```

window doesnt close.
