### ISSUE TITLE
302 Redirect during new session create fails when using Sauce Labs

### ISSUE THREAD

**Issue by lukec** [gempesaw/Selenium-Remote-Driver#312]
For users of Sauce Labs, when there are no free browsers available, your HTTP request may receive a 302 Redirect containing a Location header of where to continue the poll.

On Sauce Labs, this Location header may have a value like `/wd/hub/session/123456`

But in the `RemoteConnection::request()` an extra prefix (the `wd_context_prefix`) is added.

I'd like feedback on what a patch should look like. I think that in https://github.com/gempesaw/Selenium-Remote-Driver/blob/master/lib/Selenium/Remote/RemoteConnection.pm#L71, if the `$url` starts with a leading `/` then we should not prefix this path with anything - assume it is absolute. The `/grid/` and `else` blocks both seem to assume the `$url` does not start with `/`.

Any thoughts?

**Comment by gempesaw** [comment]
Cool, at first blush that sounds entirely reasonable. As you probably figured out, the `wd_context_prefix` is intended to allow S::R::D to communicate with servers at an arbitrary context. I can't recall if adding the absolute path check will break the current usage - I guess, the question is, do the current URLs that `::request()` process have a leading `/`?  The answer to which is ... hmm they come from `Commands.pm`, where none of them have a leading `/` in fact! So, you should be good :D

**Comment by lukec** [comment]
@gempesaw does this patch look ok to you?

**Comment by gempesaw** [comment]
fixed by #313 as aa9cd46a1a4db061aa732c95ad6c5bf0b0f0750b, thanks c:
