### ISSUE TITLE
ide-plugin.js incorrect attribute() call

### ISSUE THREAD

**Issue by Maxattax97** [gempesaw/Selenium-Remote-Driver#316]
When asserting values, the plugin improperly writes `attribute` when it should be `get_attribute`. For example:
```
is($driver->find_element("input[type=\"email\"]", "css")->attribute("value"),"abc\@email.com");
```
When it should be:
```
is($driver->find_element("input[type=\"email\"]", "css")->get_attribute("value"),"abc\@email.com");
```

[Source](http://search.cpan.org/~gempesaw/Selenium-Remote-Driver-0.2102/lib/Selenium/Remote/WebElement.pm#get_attribute)

**Comment by gempesaw** [comment]
fixed by #317
