### ISSUE TITLE
upload_file(): needs unit tests, and version check

### ISSUE THREAD

**Issue by kurmanka** [gempesaw/Selenium-Remote-Driver#37]
upload_file() needs unit tests, and needs to check that Selenium is at least 2.8.0, as it doesn't work on older versions. Original ticket context follows.

-----------------

Java and Ruby client libraries for Selenium Remote Driver have a feature for uploading a file to the host that runs the selenium server. According to this blog post, Selenium server has this feature since version 2.8.0: 
http://sauceio.com/index.php/2012/03/selenium-tips-uploading-files-in-remote-webdriver/

The file is uploaded via the /session/:sessionId/file request, which is not documented in JSONWireProtocol, or anywhere else, actually. But the functionality is essential for file upload tests in case you use a 'Selenium-on-demand' service, like the one provided by Sauce Labs.

We could implement an upload_file() method in the Selenium::Remote::Driver class. The method could issue the session/:sessionId/file request (passing the file contents encoded as expected by the server), and would return the remote server's local path to the file uploaded. That path could then be used for a send_keys() call on a correct input element.

My take on how this could be implemented is in the following commit: 
https://github.com/kurmanka/Selenium-Remote-Driver/commit/402a0a5c278e39ea7831f13f42e864fba8a2ab85

**Comment by teodesian** [comment]
Have resolved issue of not returning file, no_content_success was set incorrectly.
Added unit tests that the method returns the full filename on the remote host, and discovered a quirk of selenium.  if the file is in $CWD, it returns the full path.  if not, it returns the path to the basename of the file.  Going to make upload_file understand this behavior, and 'do the right thing'.  Should have a pull request ready later today.

**Comment by teodesian** [comment]
Hmm, I forgot to implement one of the original issues reported by the ticket author, namely to check that the version is correct.  What would be the desirable policy on this?

Should we croak, or simply return a false value?  I suppose croaking would be consistent with the rest of the module's behavior.

Anyways, I wlll have to write a separate test for behavior across various selenium versions, as each likely requires it's own mockset to be generated, and the harness only supports 1 mockset/test.

If I'm going to do that it might make sense to knock out other version testing as well; that might be it's own 'needs test' issue all by itself.  Probably a pretty hefty research task to see which functions exist when.

**Comment by gempesaw** [comment]
Honestly, I'm not too concerned about the version check. It made sense back then, but hopefully by now it's a non-issue. I can't imagine someone managing to use 2.8.0, _and_ undocumented functionality, _and_ not being able/knowing how to upgrade their version.

I'd still accept a version check PR if you're so inclined, but it can be separate from this one.

**Comment by teodesian** [comment]
Agree, I think version checks would be nice, especially for some of the new JSONwire stuff.  I might get the chance to look at this again in a few weeks, and I'll see about some reasonably comprehensive version tests then.

**Comment by gempesaw** [comment]
fixed by #178 and released in 0.23. as previously mentioned, version check PR will be considered separately. Thanks again!
