### ISSUE TITLE
document how to import and use the ide-plugin.js in the Selenium-IDE

### ISSUE THREAD

**Issue by markstos** [gempesaw/Selenium-Remote-Driver#66]
From @gordolio: "Instructions on how to import and use the ide-plugin.js in the Selenium-IDE would be handy as well. This will allow someone to have access to the Selenium::Remote::Driver grammer in the Selenium-IDE. Until such a time when we can get the ide-plugin put in to the Selenium-IDE project."

**Comment by richi235** [comment]
See #275
