### ISSUE TITLE
wish: move_to( element => ... ) should support a "search target" as well as a WebElement

### ISSUE THREAD

**Issue by markstos** [gempesaw/Selenium-Remote-Driver#88]
If you want to move the mouse to a WebElement, you can now do this:

    $s->move_to( element => $s->find_element('#id'));

I propose allowing this shorthand:

   $s->move_to( element => '#id' );

That is: If the value provided to 'element' is a string, use it as an argument to find_element() to look up and return a WebElement using the default_finder. 

+1? -1?

**Comment by gempesaw** [comment]
hm, closing this old ticket. not entirely motivated to make the change, and I'm not in favor of the added complexity of overloading the method signature. shrug, will accept a PR as usual though! :)
